### ISSUE TITLE
The label of threshold map?

### ISSUE THREAD

**Issue by saicoco** [MhLiao/DB#1]
Hi, Minghui, thanks to your nice work, here are some question to ask you:
1. "where the label of the threshold map can be generated by computing the distance
to the closest segment in G."
I think the distance is distanceTransform of pixels in border, however I add it into loss cannot be converged.  
2. "Lt is computed as the sum of L1 distances between the prediction and label inside the dilated text polygon Gd"
I think the loss for threshold map is calculated for region in border.
3. Pixels in threshold map are in [0, 1]? If so, the threshold map network predicted should process by sigmoid.  

Above all are my question and my thoughs.

**Comment by MhLiao** [comment]
@saicoco You are correct. But I am not sure why your loss cannot be converged.

**Comment by saicoco** [comment]
@MhLiao Thanks, I have solved by adding sigmod to threshold map, by the way, have you try supervised normal border map as threshold map like 'self organized text detection', and compare it in ablation study?

**Comment by MhLiao** [comment]
@saicoco We did not try it. 
The threshold map would highlight the text border region even without supervision for the threshold map. This indicates that the border-like threshold map is beneficial to the final results. Thus, we apply border-like supervision on the threshold map for better guidance. 
The threshold supervision makes the training more stable and obtains minor performance gain on some specific datasets. However, we think that it is not the key element of DB since the DB is effective even the threshold supervision is removed.

**Comment by saicoco** [comment]
@MhLiao Thanks for you detail reply, I am understand it clearly that why you add a threshold supervision😊

**Comment by Banyueqin** [comment]
@saicoco  How abount your implementation result?

**Comment by saicoco** [comment]
@Banyueqin  I implement it based psenet codebase, just add a label for threshold map, two heads for threshold map and binarization map, I dont try deformablev2.

**Comment by Banyueqin** [comment]
@saicoco Thanks for your reply, I have some problems in implementation. Can you give me some advice? I contact you with the email. Or do you have QQ?

**Comment by deepseek** [comment]
@saicoco did you post the code for your implementation

**Comment by WenmuZhou** [comment]
When two texts are close to each other, threshold map gt will also overlap, what to do at this 
![image](https://user-images.githubusercontent.com/12406017/69837733-32304600-128b-11ea-8caa-d8e4dcd5d3cb.png) 
![image](https://user-images.githubusercontent.com/12406017/69837755-4e33e780-128b-11ea-9383-c40713ff19ca.png)

**Comment by WenmuZhou** [comment]
@saicoco @Banyueqin can we communication with qq？my qq is 572459439, please note DBNet

**Comment by liangzimei** [comment]
very good work , but i have a question:
why the label of threshold map is bigger closing to G, smaller closing to Gs and Gd, rather than bigger closing to Gs and smaller closing to G.
