### ISSUE TITLE
icdar2015结果不一致相差大

### ISSUE THREAD

**Issue by shaohailin** [MhLiao/DB#100]
I make the base_icdar2015.yaml and icdar2015_resnet50_deform_thre.yaml by referencing base_totaltext.yaml and totaltext_resnet50_deform_thre.yaml.Changes are there:
![图片](https://user-images.githubusercontent.com/56865153/71607007-e554cd80-2bb0-11ea-8760-a0b6ec95fe54.png)
![图片](https://user-images.githubusercontent.com/56865153/71607017-fa316100-2bb0-11ea-9b2d-5b3a73dc442b.png)
This is my training command:
CUDA_VISIBLE_DEVICES=4,5 python train.py experiments/seg_detector/icdar2015_resnet50_deform_thre.yaml --resume Models/pre-trained-model-synthtext-resnet50 --num_gpus 2
This is my testing command and result:
![图片](https://user-images.githubusercontent.com/56865153/71607195-36b18c80-2bb2-11ea-90f0-dc6b059aecc5.png)
You can see that the result is far lower than your result in paper, could you give me some advice to reach your result?
your result:
![图片](https://user-images.githubusercontent.com/56865153/71607471-c6583a80-2bb4-11ea-9845-22dc0ad10da4.png)

one more question:
When will you release the right pre-trained-model-synthtext-resnet18 model model trained with DCN?
@MhLiao

**Comment by MhLiao** [comment]
@shaohailin I will release the model of IC15 later.
