### ISSUE TITLE
为什么图像边缘地带文字区域分数为偏低

### ISSUE THREAD

**Issue by phybrain** [MhLiao/DB#104]

**Comment by MhLiao** [comment]
边缘属于很难判断的区域，因为数据集并不是像素级别的标注的，gt本身误差较大。

**Comment by MhLiao** [comment]
@phybrain 这个现象挺有意思的，请问有具体样例吗？

**Comment by phybrain** [comment]
![image](https://user-images.githubusercontent.com/29749341/72232172-586f3280-35fa-11ea-92a8-e0ec60533dda.png)
这行字在图片最底端，分数比图片中心区域低很多，经常漏检

**Comment by Fei-Wang** [comment]
@phybrain 这种票据主要是太靠近边缘，而且离得很近，训练时数据增强RandomCropData一般会切不到。我们这里两种方法可以解决这个问题：
1. 使用同样的图片，上下堆叠来进行测试。（但是我怕左右也有这种情况）
2. 修改RandomCropData方法进行训练。
