### ISSUE TITLE
测试结果召回率偏低

### ISSUE THREAD

**Issue by oceanogeology** [MhLiao/DB#105]
按照文章的步骤来做，先在synth80k上训2个epoch，然后再CTW1500上finetune1200个epoch，结果的准确率和文章一样，但是召回率却比文章低了10个点。求解答。

**Comment by oceanogeology** [comment]
还有就是测试的时候，如果用thresh map去预测，效果明显差于用pred map去做预测。
![image](https://user-images.githubusercontent.com/38741650/71948007-97237800-3209-11ea-989b-013072bd3316.png)

**Comment by leigaoxiang** [comment]
测试的时候有没有发现老是少一个去没框住，标注数据这个区域是有的..?

**Comment by MhLiao** [comment]
@oceanogeology 训练CTW1500不太确定是什么问题。用thresh map的结果应该与用pred map的结果近似，你也可以看到你提供的两个结果里precision和recall差异非常大。你利用box_thresh将二者的precision和recall调到相当程度，最终的f-score应当是近似的。
