### ISSUE TITLE
为什么测试的时候只用到了分割预测，而不是二值化后的预测

### ISSUE THREAD

**Issue by kache1995** [MhLiao/DB#106]
`       binary = self.binarize(fuse)
        if self.training:
            result = OrderedDict(binary=binary)
        else:
            return binary  #为什么测试的时候这里返回binary，而不是返回thres_binary
        if self.adaptive and self.training:
            if self.serial:
                fuse = torch.cat(
                        (fuse, nn.functional.interpolate(
                            binary, fuse.shape[2:])), 1)
            thresh = self.thresh(fuse)
            thresh_binary = self.step_function(binary, thresh)
            result.update(thresh=thresh, thresh_binary=thresh_binary)
        return result`

**Comment by kache1995** [comment]
```       binary = self.binarize(fuse)
        if self.training:
            result = OrderedDict(binary=binary)
        else:
            return binary
        if self.adaptive and self.training:
            if self.serial:
                fuse = torch.cat(
                        (fuse, nn.functional.interpolate(
                            binary, fuse.shape[2:])), 1)
            thresh = self.thresh(fuse)
            thresh_binary = self.step_function(binary, thresh)
            result.update(thresh=thresh, thresh_binary=thresh_binary)
        return result```

**Comment by MhLiao** [comment]
论文中有讨论，我们发现使用分割预测结果并不会变差，而且模型更小速度更快。
