### ISSUE TITLE
the change of gaussian gt map

### ISSUE THREAD

**Issue by zhangchurong** [MhLiao/DB#110]
thanks for sharing your great work ! 
I want to modify the gt map to gaussian map , Surprisingly, I found some gaussian-related code in data/processes dir, but when I try to modified my yaml file to train it in gaussian-way , I found that it requested  the exact label of each characters. could you give me some advice on it ?

**Comment by MhLiao** [comment]
@zhangchurong I think it is not working for the current code. You can write your own.

**Comment by zhangchurong** [comment]
> @zhangchurong I think it is not working for the current code. You can write your own.

Thanks for your reply, I will try to modify it. And thanks again for sharing your complete training and evaluation code. It really helps a lot!

**Comment by zhangchurong** [comment]
> @zhangchurong I think it is not working for the current code. You can write your own.

Thanks for your reply, I will try to modify it. And thanks again for sharing your complete training and evaluation code. It really helps a lot!
