### ISSUE TITLE
训练过程报错 not enough values to unpack（expect 2, got 1）

### ISSUE THREAD

**Issue by Bachelorwangwei** [MhLiao/DB#111]

**Comment by MhLiao** [comment]
具体是哪一行报错？

**Comment by BaijingML** [comment]
应该是训练ICDAR2015过程中的validate，我试了把validate的batchsize设置成2就可以了
不过又报另一个错：
icdar2015_eval/detection/iou.py", line 185, in combine_results
    numGlobalCareGt += result['gtCare']
TypeError: string indices must be integers

**Comment by ChangWinnie** [comment]
@BaijingML I have same problem, do you solved this?
