### ISSUE TITLE
测试速度的时候以哪个值为准？

### ISSUE THREAD

**Issue by zhangchurong** [MhLiao/DB#112]
![image](https://user-images.githubusercontent.com/31760449/72507550-0ee34980-387f-11ea-8538-91618e4f3cbe.png)
我在测试total数据时，使用
CUDA_VISIBLE_DEVICES=0 python eval.py experiments/seg_detector/totaltext_resnet18_deform_thre.yaml --resume models/totaltext_resnet18 --polygon --box_thresh 0.7 --speed
命令，但如图所示，每跑一张图片，就会有一个FPS，我应该以哪个为准呢？
以及测试速度时与gpu型号性能有关系吗？

**Comment by shaohailin** [comment]
测试速度的时候以哪个值为准?
同问，求解答

**Comment by jotoy** [comment]
测试速度的时候以哪个值为准?
同问，求解答
