### ISSUE TITLE
训练出来的模型预测全是空；；还有训练就会停在某个时间不动了，一晚上都不动

### ISSUE THREAD

**Issue by wuzuowuyou** [MhLiao/DB#113]
生成的txt，里面都是空的，是训练不够啊？还有训练就会停在某个时间不动了，一晚上都不动

**Comment by MhLiao** [comment]
txt全空应该是模型还没训练好。我没遇到过训练停止的这种情况。

**Comment by wuzuowuyou** [comment]
训练ic15也是不收敛啊，
epoch: 6, loss: 4.869051, lr: 0.006969
降不下去，测试txt全为空

**Comment by wuzuowuyou** [comment]
不知道是不是我用的cuda8，pytorch1.0.1的缘故导致的，但是也没有报错。。

**Comment by wuzuowuyou** [comment]
[INFO] [2020-01-20 09:10:04,933] step:  43540, epoch: 172, loss: 3.450452, lr: 0.006091
[INFO] [2020-01-20 09:10:04,935] bce_loss: 0.434851
[INFO] [2020-01-20 09:10:04,936] thresh_loss: 0.424937
[INFO] [2020-01-20 09:10:04,936] l1_loss: 0.085126
[INFO] [2020-01-20 09:11:07,083] step:  43560, epoch: 172, loss: 4.329102, lr: 0.006091
[INFO] [2020-01-20 09:11:07,084] bce_loss: 0.530802
[INFO] [2020-01-20 09:11:07,085] thresh_loss: 0.632023
[INFO] [2020-01-20 09:11:07,085] l1_loss: 0.104307
[INFO] [2020-01-20 09:12:02,485] step:  43580, epoch: 172, loss: 3.806851, lr: 0.006091
[INFO] [2020-01-20 09:12:02,486] bce_loss: 0.497133
[INFO] [2020-01-20 09:12:02,486] thresh_loss: 0.474345
[INFO] [2020-01-20 09:12:02,486] l1_loss: 0.084684
[INFO] [2020-01-20 09:12:46,594] Training epoch 173 3
[INFO] [2020-01-20 09:13:07,919] step:  43600, epoch: 173, loss: 4.192158, lr: 0.006086
[INFO] [2020-01-20 09:13:07,921] bce_loss: 0.535549
[INFO] [2020-01-20 09:13:07,921] thresh_loss: 0.563978
[INFO] [2020-01-20 09:13:07,921] l1_loss: 0.095043
[INFO] [2020-01-20 09:14:28,854] step:  43620, epoch: 173, loss: 4.294724, lr: 0.006086
[INFO] [2020-01-20 09:14:28,855] bce_loss: 0.549586
[INFO] [2020-01-20 09:14:28,856] thresh_loss: 0.594483
[INFO] [2020-01-20 09:14:28,856] l1_loss: 0.095231
[INFO] [2020-01-20 09:15:46,922] step:  43640, epoch: 173, loss: 3.866090, lr: 0.006086
[INFO] [2020-01-20 09:15:46,924] bce_loss: 0.518493
[INFO] [2020-01-20 09:15:46,924] thresh_loss: 0.524028
[INFO] [2020-01-20 09:15:46,925] l1_loss: 0.074960
[INFO] [2020-01-20 09:16:43,418] step:  43660, epoch: 173, loss: 4.253732, lr: 0.006086
[INFO] [2020-01-20 09:16:43,419] bce_loss: 0.547474
[INFO] [2020-01-20 09:16:43,420] thresh_loss: 0.657923
[INFO] [2020-01-20 09:16:43,420] l1_loss: 0.085844
[INFO] [2020-01-20 09:17:51,891] step:  43680, epoch: 173, loss: 4.068015, lr: 0.006086
[INFO] [2020-01-20 09:17:51,893] bce_loss: 0.511037
[INFO] [2020-01-20 09:17:51,893] thresh_loss: 0.590102
[INFO] [2020-01-20 09:17:51,893] l1_loss: 0.092273
[INFO] [2020-01-20 09:18:39,824] step:  43700, epoch: 173, loss: 4.118070, lr: 0.006086
[INFO] [2020-01-20 09:18:39,825] bce_loss: 0.514547
[INFO] [2020-01-20 09:18:39,825] thresh_loss: 0.610297
[INFO] [2020-01-20 09:18:39,826] l1_loss: 0.093504
[INFO] [2020-01-20 09:20:07,733] step:  43720, epoch: 173, loss: 3.861124, lr: 0.006086
[INFO] [2020-01-20 09:20:07,735] bce_loss: 0.495432
[INFO] [2020-01-20 09:20:07,736] thresh_loss: 0.486409
[INFO] [2020-01-20 09:20:07,736] l1_loss: 0.089756
[INFO] [2020-01-20 09:20:59,570] step:  43740, epoch: 173, loss: 4.433690, lr: 0.006086

loss不下降。。

**Comment by MhLiao** [comment]
你能不能用readme中推荐的版本试试？你这个确实是完全没有收敛。

**Comment by MissPenguin** [comment]
请问你这个问题解决了吗，是环境问题吗，我训ic15和totaltext的loss都不降，环境版本跟作者不一样

**Comment by Ffmydy** [comment]
@wuzuowuyou 请问你gt里面的txt文件每一行结尾需“###’'吗
