### ISSUE TITLE
损失函数与论文中有些不一样

### ISSUE THREAD

**Issue by kasyoukin** [MhLiao/DB#115]
论文中
L = Ls + α × Lb + β × Lt
Ls = Lb =BCELoss
代码中
Ls是DiceLoss
这是什么原因？

**Comment by MhLiao** [comment]
@kasyoukin 代码中有dice loss的选项，可能打印出来的名称有问题，但是默认用的依然是BCE。

**Comment by liangzimei** [comment]
默认使用的L1BalanceCELoss里好像确实用了dice loss

**Comment by ZhengMengbin** [comment]
所以到底得用哪个损失函数，我debug运行，Ls确实使用的是DiceLoss而不是BCELoss

**Comment by tangzhongliang** [comment]
the problem in L1BalanceCELoss function:
1.
    Ls:  probability map  in paper is writen as binary
    Lt:  thresh map in paper is writen as thresh 
    Lb: binary map in paper is writen as thresh_binary
2.
    L = Ls + α × Lb + β × Lt is writen as: L = Loss(thresh_binary) + α × Loss(thresh )+ β × Loss(binary)

**Comment by zhangqianYY** [comment]
@MhLiao 代码里面Ls的确是用的DiceLoss，有什么解释么

**Comment by zhangqianYY** [comment]
@MhLiao 损失函数系数代码中和paper中也不同
