### ISSUE TITLE
报错：/DB_office-master/assets/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by xumoremore** [MhLiao/DB#116]
你好，我运行demo的时候报上面的错，因为运行这条命令安装太慢（conda install pytorch torchvision cudatoolkit=10.1 -c pytorch），所以我改成国内镜像源下载，使用这个命令（conda install pytorch torchvision cudatoolkit=10.0）。不知道是不是因为这个原因报上面的错

**Comment by MhLiao** [comment]
你这个应该是DCN编译出错了导致的。

**Comment by fengdashuai** [comment]
> 你好，我运行demo的时候报上面的错，因为运行这条命令安装太慢（conda install pytorch torchvision cudatoolkit=10.1 -c pytorch），所以我改成国内镜像源下载，使用这个命令（conda install pytorch torchvision cudatoolkit=10.0）。不知道是不是因为这个原因报上面的错

请问这个问题解决了吗

**Comment by BaijingML** [comment]
我好像解决了，就是重装了一次pytorch，用CUDA10.1，然后重新把dcn编译一下，编译之前把build文件和.so文件都删了。不用谢，我叫雷锋。

**Comment by fengdashuai** [comment]
谢谢✧٩(ˊωˋ*)و✧


 
---原始邮件---
发件人: "BaijingML"<notifications@github.com&gt;
发送时间: 2020年3月1日 21:59:08
收件人: "MhLiao/DB"<DB@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"fengdashuai"<2106714944@qq.com&gt;;
主题: Re: [MhLiao/DB] 报错：/DB_office-master/assets/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs (#116)



我好像解决了，就是重装了一次pytorch，用CUDA10.1，然后重新把dcn编译一下，编译之前把build文件和.so文件都删了。不用谢，我叫雷锋。

**Comment by BaijingML** [comment]
> 谢谢✧٩(ˊωˋ*)و✧
> […](#)
> ---原始邮件--- 发件人: "BaijingML"<notifications@github.com&gt; 发送时间: 2020年3月1日 21:59:08 收件人: "MhLiao/DB"<DB@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"fengdashuai"<2106714944@qq.com&gt;; 主题: Re: [MhLiao/DB] 报错：/DB_office-master/assets/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs (#116) 我好像解决了，就是重装了一次pytorch，用CUDA10.1，然后重新把dcn编译一下，编译之前把build文件和.so文件都删了。不用谢，我叫雷锋。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

貌似还是有点问题，上面的问题解决了，这次跑demo的时候报段错误。。。
