### ISSUE TITLE
demo.py  segmentation fault

### ISSUE THREAD

**Issue by LJXLJXLJX** [MhLiao/DB#121]
> $ CUDA_VISIBLE_DEVICES=0 python demo.py experiments/seg_detector/totaltext_resnet18_deform_thre.yaml --image_path ~/DataSet/type1/nioqfkxiir.jpg --resume models/totaltext_resnet18 --polygon --box_thresh 0.7 --visualiz
> [1]    1903389 segmentation fault (core dumped)  CUDA_VISIBLE_DEVICES=3 python demo.py  --image_path  --resume  --polygon  0.7

**Comment by LJXLJXLJX** [comment]
I'm not sure if I successfully compiled DCN.

> $ python setup.py build_ext --inplace                                                                      <<<
> running build_ext
> building 'deform_pool_cuda' extension
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -                                                       pipe -fno-plt -fno-semantic-interposition -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=                                                       generic -O3 -pipe -fno-plt -fPIC -I/usr/lib/python3.8/site-packages/torch/include -I/usr/lib/python3.8/site-pac                                                       kages/torch/include/torch/csrc/api/include -I/usr/lib/python3.8/site-packages/torch/include/TH -I/usr/lib/pytho                                                       n3.8/site-packages/torch/include/THC -I/opt/cuda/include -I/usr/include/python3.8 -c src/deform_pool_cuda.cpp -                                                       o build/temp.linux-x86_64-3.8/src/deform_pool_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=def                                                       orm_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
> /opt/cuda/bin/nvcc -I/usr/lib/python3.8/site-packages/torch/include -I/usr/lib/python3.8/site-packages/torch/in                                                       clude/torch/csrc/api/include -I/usr/lib/python3.8/site-packages/torch/include/TH -I/usr/lib/python3.8/site-pack                                                       ages/torch/include/THC -I/opt/cuda/include -I/usr/include/python3.8 -c src/deform_pool_cuda_kernel.cu -o build/                                                       temp.linux-x86_64-3.8/src/deform_pool_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__                                                        -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSIO                                                       N_H -DTORCH_EXTENSION_NAME=deform_pool_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_61,code=sm_61 -std                                                       =c++11
> g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fno-semantic-interposition -Wl,-O1,--so                                                       rt-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.8/src/deform_pool_cuda.o build/temp.linux-x86_6                                                       4-3.8/src/deform_pool_cuda_kernel.o -L/opt/cuda/lib64 -L/usr/lib -lcudart -o build/lib.linux-x86_64-3.8/deform_                                                       pool_cuda.cpython-38-x86_64-linux-gnu.so
> copying build/lib.linux-x86_64-3.8/deform_conv_cuda.cpython-38-x86_64-linux-gnu.so ->
> copying build/lib.linux-x86_64-3.8/deform_pool_cuda.cpython-38-x86_64-linux-gnu.so ->

**Comment by LJXLJXLJX** [comment]
在docker里面就能成功运行 本机就不行 很迷。。。

**Comment by duydangg** [comment]
have you solved it 
same problem here 
**running build_ext
copying build/lib.linux-x86_64-3.7/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so -> 
copying build/lib.linux-x86_64-3.7/deform_pool_cuda.cpython-37m-x86_64-linux-gnu.so ->**

**Comment by LJXLJXLJX** [comment]
> have you solved it
> same problem here
> **running build_ext copying build/lib.linux-x86_64-3.7/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so -> copying build/lib.linux-x86_64-3.7/deform_pool_cuda.cpython-37m-x86_64-linux-gnu.so ->**

Try Docker
