### ISSUE TITLE
两个问题，训练保存和多卡训练

### ISSUE THREAD

**Issue by yh673025667** [MhLiao/DB#128]
1.训练保存不能自己指定保存路径吗？只能是默认的保存在output文件夹？
2.多卡训练的时候还是会提示缺少参数‘data’这个错误，请问怎么解决呢（单卡训练是正常的）

期待解答，谢谢

**Comment by BaijingML** [comment]
你好，请问多卡训练缺少data是怎么解决的？调整的代码有点多，我糊涂了

**Comment by BaijingML** [comment]
貌似是因为validate的batchsize和卡的数量要一致，但这样改了还有报错：
line 185, in combine_results
    numGlobalCareGt += result['gtCare']
TypeError: string indices must be integers
这个你遇到过嘛？

**Comment by yh673025667** [comment]
@BaijingML 这个问题我就没解决，我的多卡报的错和你的不一样，error in modulated_deformable_col2im_cuda: no kernel image is available for execution on the device。
我的是epoch0的训练过程中报的这个错，log日志还能打印一点训练日志，很奇怪

**Comment by yh673025667** [comment]
@MhLiao 我的是执行到这一步的时候会随机报错，negative_loss, _ = torch.topk(negative_loss.view(-1), negative_count)
单卡和多卡都有可能随机出现这个错误，很奇怪

**Comment by BaijingML** [comment]
> @MhLiao 我的是执行到这一步的时候会随机报错，negative_loss, _ = torch.topk(negative_loss.view(-1), negative_count)
> 单卡和多卡都有可能随机出现这个错误，很奇怪

其实我说错了，上面的解决方法是错的。
你后面说的两个问题我没遇到过。
不过代码确实有bug，我改了之后好了：
raw_metric, interested = self.structure.measurer.validate_measure(batch, output) 这句代码要返回两个值，但你要是点开self.structure.measurer.validate_measure函数，就会发现，ICDARDetectionMeasurer类里的validate_measure返回了两个值，但QuadMeasurer类的validate_measure只返回了一个值，所以像ICDARDetectionMeasurer类那样给QuadMeasurer的validate_measure补一个默认False的值就可以了。即        
return self.measure(batch, output, is_output_polygon, box_thresh), [int(self.visualized)]
记得把self.visualized添加到类变量里。

**Comment by BaijingML** [comment]
> @BaijingML 这个问题我就没解决，我的多卡报的错和你的不一样，error in modulated_deformable_col2im_cuda: no kernel image is available for execution on the device。
> 我的是epoch0的训练过程中报的这个错，log日志还能打印一点训练日志，很奇怪

你的这个问题应该是Deconv没有编译好，重新配置吧

**Comment by yh673025667** [comment]
> > @BaijingML 这个问题我就没解决，我的多卡报的错和你的不一样，error in modulated_deformable_col2im_cuda: no kernel image is available for execution on the device。
> > 我的是epoch0的训练过程中报的这个错，log日志还能打印一点训练日志，很奇怪
> 
> 你的这个问题应该是Deconv没有编译好，重新配置吧

编译好了，我们的训练环境环境是docker，我现在单卡跑inference，eval，以及训练都正常的，就偶尔单卡训练在刚开始时会出这个bug，多卡必报这个错误，没搞懂问题在哪

**Comment by yh673025667** [comment]
训练的机器有问题，目前单卡多卡训练测试均正常

**Comment by ZhengMengbin** [comment]
@yh673025667 @oftenliu 你们应该是没有加这个指定GPU的字段“CUDA_VISIBLE_DEVICES=0,1,2,3”
