### ISSUE TITLE
segmentation fault(core dumped)

### ISSUE THREAD

**Issue by Haofun123** [MhLiao/DB#13]

**Comment by MhLiao** [comment]
@Haofun123 Please give more information.

**Comment by Haofun123** [comment]
![image](https://user-images.githubusercontent.com/18555185/70129696-34930580-16ba-11ea-85bb-243d557d59bd.png)

**Comment by MhLiao** [comment]
Have you built the DCN successfully?

**Comment by ChangWinnie** [comment]
> Have you built the DCN successfully?
Excuse me,
I built the DCN successfully but still show this message,
how to solve this issue?
Thanks for your reply.

<img width="486" alt="螢幕快照 2020-02-19 00 34 07" src="https://user-images.githubusercontent.com/55385048/74757139-93771c80-52b0-11ea-8434-6d7eb61ddaff.png">

**Comment by minh132** [comment]
verbose: True
Initializing log dir for workspace/SegDetectorModel-seg_detector/deformable_resnet50/L1BalanceCELoss
./datasets/icdar2015/
Resumed from /home/iwanna/Documents/idcard/DB/pretrained/synthtext_finetune_ic15_res50_dcn_fpn_dbv2_thresh0.25
export.sh: line 1:  4200 Segmentation fault      (core dumped) python convert_to_onnx.py /home/iwanna/Documents/idcard/DB/experiments/seg_detector/ic15_resnet50_deform_thre.yaml /home/iwanna/Documents/idcard/DB/pretrained/synthtext_finetune_ic15_res50_dcn_fpn_dbv2_thresh0.25 /home/iwanna/Documents/idcard/DB/model_onnx.onnx

I meet this error when convert to onnx . Can you help me @MhLiao
