### ISSUE TITLE
能否支持Multi-Scale Training 和Testing呢？

### ISSUE THREAD

**Issue by yh673025667** [MhLiao/DB#133]
@MhLiao 您好，请问一下，这个代码能否支持多尺度训练和测试呢？

**Comment by MhLiao** [comment]
@yh673025667 暂不支持

**Comment by yh673025667** [comment]
> @yh673025667 暂不支持

@MhLiao 谢谢回复，另外最后一个问题就是，您在V100上训练过吗？这套代码在P40上能正常跑（单卡，多卡，eval等等），但是在V100上就跑不了，单卡都会报错。我不知道是因为代码的问题还是硬件的问题。报的是关于dcn里面的cuda错误:(

**Comment by MhLiao** [comment]
@yh673025667 你换卡是否重新编译了？因为一般一台机器上所有卡是一样的，所以我没试过直接换卡。

**Comment by yh673025667** [comment]
@MhLiao 是的，重新编译了的，如果不重新编译就会报错

**Comment by yh673025667** [comment]
@MhLiao 问题已经解决了，就是需要重新编译一下:)
