### ISSUE TITLE
百度云盘上没有icdar2015训练好的模型

### ISSUE THREAD

**Issue by jiechen99** [MhLiao/DB#135]
你好，看了下，google drive上有icdar2015训练好的模型，然而在百度云盘上没有。能否在百度云盘上也传一份。google drive下载文件太慢了。非常感谢。

**Comment by MhLiao** [comment]
@jiechen99 百度云已上传

**Comment by jiechen99** [comment]
谢谢~

**Comment by Tian14267** [comment]
百度云里并没有啊 @MhLiao @jiechen99
