### ISSUE TITLE
训练遇到点问题，求解答，除了thresh_loss其他loss都为0

### ISSUE THREAD

**Issue by luqiang6q** [MhLiao/DB#148]
[INFO] [2020-03-31 17:01:29,493] Training epoch 0
[INFO] [2020-03-31 17:01:44,182] step:      0, epoch:   0, loss: 1.000000, lr: 0.007000
[INFO] [2020-03-31 17:01:44,187] bce_loss: 0.000000
[INFO] [2020-03-31 17:01:44,188] thresh_loss: 1.000000
[INFO] [2020-03-31 17:01:44,188] l1_loss: 0.000000

**Comment by luqiang6q** [comment]
@MhLiao

**Comment by luqiang6q** [comment]
我是用自己的数据训练的，gt中的坐标是顺时针

**Comment by luqiang6q** [comment]
@MhLiao 而且训练了loss一直都是这样。。。

**Comment by rfdeng** [comment]
> @MhLiao 而且训练了loss一直都是这样。。。



> [INFO] [2020-03-31 17:01:29,493] Training epoch 0
> [INFO] [2020-03-31 17:01:44,182] step: 0, epoch: 0, loss: 1.000000, lr: 0.007000
> [INFO] [2020-03-31 17:01:44,187] bce_loss: 0.000000
> [INFO] [2020-03-31 17:01:44,188] thresh_loss: 1.000000
> [INFO] [2020-03-31 17:01:44,188] l1_loss: 0.000000



> [INFO] [2020-03-31 17:01:29,493] Training epoch 0
> [INFO] [2020-03-31 17:01:44,182] step: 0, epoch: 0, loss: 1.000000, lr: 0.007000
> [INFO] [2020-03-31 17:01:44,187] bce_loss: 0.000000
> [INFO] [2020-03-31 17:01:44,188] thresh_loss: 1.000000
> [INFO] [2020-03-31 17:01:44,188] l1_loss: 0.000000

请问这个问题解决了么，是因为数据集预处理的问题么？

**Comment by rfdeng** [comment]
> [INFO] [2020-03-31 17:01:29,493] Training epoch 0
> [INFO] [2020-03-31 17:01:44,182] step: 0, epoch: 0, loss: 1.000000, lr: 0.007000
> [INFO] [2020-03-31 17:01:44,187] bce_loss: 0.000000
> [INFO] [2020-03-31 17:01:44,188] thresh_loss: 1.000000
> [INFO] [2020-03-31 17:01:44,188] l1_loss: 0.000000

您好，请问问题解决了么，我也遇到了同样的情况，是数据预处理的问题么？

**Comment by jalola** [comment]
Hi,
What is the reason and did you figure out how to the solution?

**Comment by jalola** [comment]
I found the reason, the my gt is not correct.
I should set the text as '0' at the end

**Comment by Ffmydy** [comment]
@jalola   how to set the text in gt file?

**Comment by jalola** [comment]
for example like this:
`655.10681185,45.75529869,1264.34652568,41.84317438,1264.44709054,113.41936054,656.00058656,117.15264391,0`
The last one is text, it should be 0 or anything except 1 or ### because 1 or ### are marked as ignored tags and the model will skip those boxes with 1 or ###

**Comment by 619268640** [comment]
@jalola 请问一下，数据格式是按你提示的做的，但loss还是0，你知道是怎么回事吗？

**Comment by jalola** [comment]
@619268640 
you should check the dataset.py to see how label is read
https://github.com/MhLiao/DB/blob/master/data/image_dataset.py#L75

check if input (mask) is correct before training (save the image of mask and check it yourself first)
https://github.com/MhLiao/DB/blob/master/data/make_seg_detector_data.py#L68
For example, I usually check if the input is correct generated:

import random
_id = str(random.randint(1, 100))
cv2.imwrite("./tmp/" + _id + "_image.jpg", data["image"])
cv2.imwrite("./tmp/" + _id + "_mask.jpg", (data["mask"] * 255).astype("uint8"))
cv2.imwrite("./tmp/" + _id + "_gt.jpg", (data["gt"][0] * 255).astype("uint8"))

**Comment by 619268640** [comment]
@jalola 谢谢，我好像找到了问题所在。

在这之前，遇到一个问题：ValueError: cannot reshape array of size 1 into shape (4, 2)
看了 issues 中的解决方法[#275](url)
把[https://github.com/MhLiao/DB/blob/master/data/processes/augment_data.py#L72](url)改为：
new_polys = np.array([[p.x, p.y] for p in keypoints]).reshape([-1, 1, 2])
在训练时 loss 仍然为 0

而我这里需要改为：
new_polys = np.array([[p.x, p.y] for p in keypoints]).reshape([-1, 4, 2])
