### ISSUE TITLE
nn.DataParallel问题

### ISSUE THREAD

**Issue by Bachelorwangwei** [MhLiao/DB#155]
SegDetectorModel在创建的时候，我没用分布式训练，因此是nn.DataParallel类。训练完，在模型inference的时候，发现创建self.model = nn.DataParallel(BasicModel(args)) 与self.model=BasicModel(args)跑完的结果不同， parallel结果正确，而直接用basicmodel，什么都检测不到。 通过定位发现，backbone跑完的结果，都不一致。
请问这是什么原因导致的，必须要用nn.dataparallel创建模型吗？

**Comment by KornBerg** [comment]
什么原因？我也发现了
