### ISSUE TITLE
同样的数据集在resnet18 backbone上训练报错

### ISSUE THREAD

**Issue by xuweidongkobe** [MhLiao/DB#169]
数据集在resnet50 backbone上可以成功训练，将yaml文件中backbone从resnet50修改为resnet18后，重新训练。报如下错误，请问是什么原因？谢谢
![1591088922(1)](https://user-images.githubusercontent.com/25764883/83502566-60ba0280-a4f4-11ea-8466-6e126450acd4.jpg)

**Comment by MhLiao** [comment]
我猜测可能是resume的model不匹配
