### ISSUE TITLE
测试结果图中的区别？

### ISSUE THREAD

**Issue by ZhengMengbin** [MhLiao/DB#172]
给出的测试结果图前后有什么区别，就是加'(paper)'和不加的测试结果区别在哪？只是调整了box_thre还是有其他训练上的区别，比如输入的图像大小等等？
![image](https://user-images.githubusercontent.com/26650043/84729261-d5497280-afc5-11ea-91fe-b42ad2203238.png)

**Comment by MhLiao** [comment]
这是重新复现的模型，paper是指原论文的模型。
