### ISSUE TITLE
when I validate the code ,it happen to the solve。@MhLiao

### ISSUE THREAD

**Issue by Ffmydy** [MhLiao/DB#178]
![图片](https://user-images.githubusercontent.com/38275987/85647766-ca7f9380-b6d1-11ea-9c58-5314113958a5.png)

**Comment by Ffmydy** [comment]
@MhLiao

**Comment by sssimpleboy** [comment]
您好。两年前的模型了。请问您还记得怎么解决这个问题吗？  我看那个measure函数明明只返回了一个list。。

**Comment by sssimpleboy** [comment]
您好。请问您还记得怎么解决这个问题吗？
你这里是 not enough  我那里是too many.   我看那个函数的返回值就一个list.
