### ISSUE TITLE
dhc 编译出错

### ISSUE THREAD

**Issue by daixiangzi** [MhLiao/DB#187]
File "setup.py", line 15, in <module>
    cmdclass={'build_ext': BuildExtension})
raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

pytorch:1.5
cuda10.1

**Comment by huangyuan2020** [comment]
我也遇到了这个问题，我发现是我使用的Pytorch版本太高，换回了pytorch1.4，现在编译成功了

**Comment by HusterRC** [comment]
我也遇到和你一样的问题，将pytorch从1.5降为1.4就可以了

**Comment by zxf864823150** [comment]
这个问题是因为在编译DCN时使用的接口是1.4，在1.6中AT_CHECK已经改为了TORCH_CHECK，只要那cpp种的AT改掉就可以编译通过了

**Comment by DerekRay** [comment]
> 这个问题是因为在编译DCN时使用的接口是1.4，在1.6中AT_CHECK已经改为了TORCH_CHECK，只要那cpp种的AT改掉就可以编译通过了

很有用 省去降级版本的麻烦 感谢！！

**Comment by sapphireh** [comment]
> 这个问题是因为在编译DCN时使用的接口是1.4，在1.6中AT_CHECK已经改为了TORCH_CHECK，只要那cpp种的AT改掉就可以编译通过了

修改./assets/ops/dcn/src 下的两个cpp文件，将里面所有的AT_CHECK改为TORCH_CHECK即可编译成功
