### ISSUE TITLE
Question about eq. 2

### ISSUE THREAD

**Issue by Lele-Xie** [MhLiao/DB#2]
After inputting the probability map and threshold map into eq.2, what post processing should we do for the fianl results? Particularly, if P equal to T, the output is a median value (1/2). It seems that there are many noises in the final binary map, so can you tell us the detailed inference?
Thank you~

**Comment by MhLiao** [comment]
@Lele-Xie cv2.findContours is enough to obtain good results from the binary map.

**Comment by Lele-Xie** [comment]
@MhLiao OK, got it. Thank you~
