### ISSUE TITLE
train的时候出现这个错误

### ISSUE THREAD

**Issue by wangning7149** [MhLiao/DB#20]
python train.py ./experiments/seg_detector/base_totaltext.yaml --num_gpus 2

Traceback (most recent call last):
  File "train.py", line 70, in <module>
    main()
  File "train.py", line 60, in main
    experiment_args = conf.compile(conf.load(args['exp']))['Experiment']
KeyError: 'Experiment'

**Comment by liangkaihuan** [comment]
don't use any base*.yaml as config file, refer to [https://github.com/MhLiao/DB/blob/master/README.md#config-file](url)
