### ISSUE TITLE
python setup.py build_ext --inplace出现错误

### ISSUE THREAD

**Issue by MTCai** [MhLiao/DB#21]
/usr/local/cuda:/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc -I/home/nmt/anaconda3/envs/pytorch1_2/lib/python3.6/site-packages/torch/include -I/home/nmt/anaconda3/envs/pytorch1_2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/nmt/anaconda3/envs/pytorch1_2/lib/python3.6/site-packages/torch/include/TH -I/home/nmt/anaconda3/envs/pytorch1_2/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda:/usr/local/cuda-9.0/include -I/home/nmt/anaconda3/envs/pytorch1_2/include/python3.6m -c src/deform_conv_cuda_kernel.cu -o build/temp.linux-x86_64-3.6/src/deform_conv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=deform_conv_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
unable to execute '/usr/local/cuda:/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command '/usr/local/cuda:/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

试过更改.brashrc的CUDA的环境变量，但是不行，这个问题要怎么解决?

**Comment by 1996leo** [comment]
同问+1

**Comment by MhLiao** [comment]
建议检查以下CUDA_HOME，以及默认cuda路径的版本是否与pytorch的一致。

**Comment by 1996leo** [comment]
> 建议检查以下CUDA_HOME，以及默认cuda路径的版本是否与pytorch的一致。

error: command 'D:\\NVIDIA_Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 2请问这个问题应如何解决

**Comment by MhLiao** [comment]
Make sure your CUDA path of $CUDA_HOME is the same version as your CUDA in PyTorch by the command of `echo $CUDA_HOME`. If not, you need to change the `$CUDA_HOME` by `export CUDA_HOME=path-of-another-version' or re-install PyTorch with the same CUDA version as in `CUDA_HOME`.

**Comment by ouguozhen** [comment]
@MhLiao 能否在python2下编译呢？

**Comment by Tian14267** [comment]
请问楼主问题解决了吗？我的pytorch==1.0.0   cuda == 9.0。遇到跟你一样的问题。请问怎么解决啊。 @ @MTCai @MhLiao @suntianlei2019102967

**Comment by fujingling** [comment]
遇到了同样的问题，惆怅中

**Comment by fujingling** [comment]
我是编译通过，运行eval.py时报错DB/assets/ops/dcn/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by xray1111** [comment]
@fujingling @Tian14267 请问你们编译错误的问题是怎么解决的啊？
