### ISSUE TITLE
关于SynthText数据集问题！

### ISSUE THREAD

**Issue by Eatzhy** [MhLiao/DB#211]
FileNotFoundError: [Errno 2] No such file or directory: 'ocr/SynthText/detection/128/person_89_99.jpg'
报错说文件下没128文件和这个图，看了下确实没有。想问大家的这个数据集总共是40多G吗，图片是分下面子文件夹吗。
1   100  102  104  106  108  152  32  73  91  93  95  97  99
10  101  103  105  107  111  176  55  90  92  94  96  98
我的是不是少了啊！！！！

**Comment by aiboys** [comment]
Hi,
我似乎在处理synthtext也遇到了一些问题，在dbtarget生成的时候会出错
