### ISSUE TITLE
cpu infer error

### ISSUE THREAD

**Issue by JianxinYuan** [MhLiao/DB#216]
Q: I used 2 GPUs to train DBNet(backbone is resnet18, without dcn). After training, I can infer with GPU, but the cpu cannot infer.

Note: dcn is not used, resnet18 is used.

**Comment by mostafahadian** [comment]
Any update on this?

**Comment by giangbang** [comment]
If you are still interested in running DB with CPU, consider taking a look at [this repo](https://github.com/giangbang/Pure-Pytorch-implementation-Deformable-Convolution).
