### ISSUE TITLE
how to test on a single image?

### ISSUE THREAD

**Issue by jinfagang** [MhLiao/DB#22]
Any scripts test on a single image?

**Comment by CaiQiuYu** [comment]
+1 同求这样一个脚本

**Comment by Excalibur0214** [comment]
> Any scripts test on a single image?

data/image_dataset.py中get_all_sample函数里做一点修改就好了，不麻烦

**Comment by jinfagang** [comment]
```
def get_all_samples(self):
        for i in range(len(self.data_dir)):
            with open(self.data_list[i], 'r') as fid:
                image_list = fid.readlines()
            if self.is_training:
                image_path=[self.data_dir[i]+'/train_images/'+timg.strip() for timg in image_list]
                gt_path=[self.data_dir[i]+'/train_gts/'+timg.strip()+'.txt' for timg in image_list]
            else:
                image_path=[self.data_dir[i]+'/test_images/'+timg.strip() for timg in image_list]
                print(self.data_dir[i])
                if 'TD500' in self.data_list[i] or 'total_text' in self.data_list[i]:
                    gt_path=[self.data_dir[i]+'/test_gts/'+timg.strip()+'.txt' for timg in image_list]
                else:
                    gt_path=[self.data_dir[i]+'/test_gts/'+'gt_'+timg.strip().split('.')[0]+'.txt' for timg in image_list]
            self.image_paths += image_path
            self.gt_paths += gt_path
        self.num_samples = len(self.image_paths)
        self.targets = self.load_ann()
        if self.is_training:
            assert len(self.image_paths) == len(self.targets)
```


Get image path then what?

**Comment by Excalibur0214** [comment]
> ```
> def get_all_samples(self):
>         for i in range(len(self.data_dir)):
>             with open(self.data_list[i], 'r') as fid:
>                 image_list = fid.readlines()
>             if self.is_training:
>                 image_path=[self.data_dir[i]+'/train_images/'+timg.strip() for timg in image_list]
>                 gt_path=[self.data_dir[i]+'/train_gts/'+timg.strip()+'.txt' for timg in image_list]
>             else:
>                 image_path=[self.data_dir[i]+'/test_images/'+timg.strip() for timg in image_list]
>                 print(self.data_dir[i])
>                 if 'TD500' in self.data_list[i] or 'total_text' in self.data_list[i]:
>                     gt_path=[self.data_dir[i]+'/test_gts/'+timg.strip()+'.txt' for timg in image_list]
>                 else:
>                     gt_path=[self.data_dir[i]+'/test_gts/'+'gt_'+timg.strip().split('.')[0]+'.txt' for timg in image_list]
>             self.image_paths += image_path
>             self.gt_paths += gt_path
>         self.num_samples = len(self.image_paths)
>         self.targets = self.load_ann()
>         if self.is_training:
>             assert len(self.image_paths) == len(self.targets)
> ```
> 
> Get image path then what?

just simply change image_path to your single image, and change the gt simultaneously

**Comment by MhLiao** [comment]
I have added a demo script to test a single image.

**Comment by ZhengMengbin** [comment]
@jinfagang Just like follows:
`    def get_all_samples(self):
        # for i in range(len(self.data_dir)):
        #     with open(self.data_list[i], 'r') as fid:
        #         image_list = fid.readlines()
        #     if self.is_training:
        #         image_path=[self.data_dir[i]+'/train_images/'+timg.strip() for timg in image_list]
        #         gt_path=[self.data_dir[i]+'/train_gts/'+timg.strip()+'.txt' for timg in image_list]
        #     else:
        #         image_path=[self.data_dir[i]+'/test_images/'+timg.strip() for timg in image_list]
        #         print(self.data_dir[i])
        #         if 'TD500' in self.data_list[i] or 'total_text' in self.data_list[i]:
        #             gt_path=[self.data_dir[i]+'/test_gts/'+timg.strip()+'.txt' for timg in image_list]
        #         else:
        #             gt_path=[self.data_dir[i]+'/test_gts/'+'gt_'+timg.strip().split('.')[0]+'.txt' for timg in image_list]
        #     self.image_paths += image_path
        #     self.gt_paths += gt_path
        # self.num_samples = len(self.image_paths)
        # self.targets = self.load_ann()
        # if self.is_training:
        #     assert len(self.image_paths) == len(self.targets)
        self.image_paths = 'datasets/total_text/test_images/151494336.jpg'
        self.gt_paths = ''
        self.num_samples = 1
        self.targets = None`

**Comment by ZhengMengbin** [comment]
@jinfagang Just like follows:
![image](https://user-images.githubusercontent.com/26650043/84626441-aa084a00-af17-11ea-821b-5f324c06e38a.png)

**Comment by Jialiang123** [comment]
How do I batch test multiple images?
