### ISSUE TITLE
Extracting rectangle instead of polygon

### ISSUE THREAD

**Issue by spoorgholi74** [MhLiao/DB#224]
When you use the box_score_fast function to create the mask and get the mean score it does not work well for extracting box annotation because the pred value is meant at the pixel level for text polygon and lots of pixels when fitting a rectangle to a polygon have value 0 (background) as can be seen in the image below which is showing the mask for the word "pepper" in the original image.
I was wondering if you have any better recommendations on extracting rectangles on the polygons.
![api_call](https://user-images.githubusercontent.com/53820154/104938774-d0abc900-59af-11eb-96c8-e480c37bcce3.jpg)
![myplot](https://user-images.githubusercontent.com/53820154/104938720-ba9e0880-59af-11eb-97f4-3637b8d2e649.png)

**Comment by hua1024** [comment]
Hai , I met the same problem, do you have a good solution

**Comment by hua1024** [comment]
> When you use the box_score_fast function to create the mask and get the mean score it does not work well for extracting box annotation because the pred value is meant at the pixel level for text and lots of pixels when fitting a rectangle to a polygon have value 0 (background) as can be seen in the image below which is showing the mask for the word "pepper" in the original image.
> I was wondering if you have any better recommendations on extracting rectangles on the polygons.
> ![api_call](https://user-images.githubusercontent.com/53820154/104938774-d0abc900-59af-11eb-96c8-e480c37bcce3.jpg)
> ![myplot](https://user-images.githubusercontent.com/53820154/104938720-ba9e0880-59af-11eb-97f4-3637b8d2e649.png)

I met the same problem, do you have a good solution

**Comment by spoorgholi74** [comment]
@hua1024 If you want to get all the boxes you can just reduce the box_thresh to get all the boxes. However, I was a bit wrong up there as cv2.mean(image, mask) calculates the mean of the image within the mask and the mask is already a rotated rectangle calculated using cv2.minareadrect.

I also tried getting the transformation matrix and crop the image more accurate but as I said cv2.mean() get the mean in the mask which is already kind of the best you can get.

If you wanna take a look at transformation and rotating the image [take a look at this blog](https://jdhao.github.io/2019/02/23/crop_rotated_rectangle_opencv/)
