### ISSUE TITLE
数据样例里面的label有很多坐标点，这个是怎么组织的啊？另外对应的图片数据在哪里下载啊？

### ISSUE THREAD

**Issue by CaiQiuYu** [MhLiao/DB#24]
还有一个问题就是，对于只有四个坐标点的数据怎么转换到和你这个一样的标签上

**Comment by MhLiao** [comment]
[这里](https://github.com/MhLiao/DB/blob/df1e029943a11ae8dd11059ac30732a7e9e76c71/data/image_dataset.py#L56https://github.com/MhLiao/DB/blob/df1e029943a11ae8dd11059ac30732a7e9e76c71/data/image_dataset.py#L56)是读取label的代码。你看看应该就知道标签应该转成什么样。每行是一个包围盒，分别是x1, y1, x2, y2 ......

**Comment by CaiQiuYu** [comment]
> [这里](https://github.com/MhLiao/DB/blob/df1e029943a11ae8dd11059ac30732a7e9e76c71/data/image_dataset.py#L56https://github.com/MhLiao/DB/blob/df1e029943a11ae8dd11059ac30732a7e9e76c71/data/image_dataset.py#L56)是读取label的代码。你看看应该就知道标签应该转成什么样。每行是一个包围盒，分别是x1, y1, x2, y2 ......

感谢，明白了
