### ISSUE TITLE
Evaluate precision . recall and f-measure are all zero.

### ISSUE THREAD

**Issue by ChangWinnie** [MhLiao/DB#249]
I add a few conv layers in seg_detector.py and training on synthtext and icdar2015, but the result is below.
![1619973420829](https://user-images.githubusercontent.com/55385048/116853656-02783100-ac29-11eb-8702-fc369d2d7afe.jpg)
while my tensorboard shows result correctly.
![1619973690530](https://user-images.githubusercontent.com/55385048/116853673-07d57b80-ac29-11eb-993b-a921468eb48c.jpg)

**Comment by ChangWinnie** [comment]
Same problem [https://github.com/MhLiao/DB/issues/148#issuecomment-644005660](url)

**Comment by Bilallbayrakdar** [comment]
What was the solution ? The link that you shared is unavailable now .
