### ISSUE TITLE
为什么代码结构要搞这么复杂？

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#25]
当然我们相信各位的工作，相信速度很快，我们不需要再去测试速度，我觉得没什么意义，我们需要的是简单的加载模型，进行预测。现在的代码是各种类，各种跳转，各种参数还不知道啥意思。。。。好南。。。。。。。。

**Comment by fujingling** [comment]
作者开源就已经很优秀了，你还抱怨，代码结构复杂你就自己慢慢读

**Comment by LanWong1** [comment]
> 作者开源就已经很优秀了，你还抱怨，代码结构复杂你就自己慢慢读

哈哈 ，这哪里是抱怨，这是抱头求助啊。大神是不能理解菜鸟的心情的。代码也是要简单易读的嘛，这代码看起来各种高大上，也不好改动。我想自己加载模型，但是呢这个加载模型还需要各种args，叫我如何下手啊。CPU的好想还跑不了。。。。。要不大神你搞一个跑单张图的脚本，支持cpu，万分感谢啊？

**Comment by MhLiao** [comment]
我之后会加一个跑单张图的脚本，不过这几天有事，可能要下周，你可以先试试[这个](https://github.com/MhLiao/DB/issues/22#issuecomment-562018764)。我们做实验的时候尝试了很多设置和搭配，所以代码结构有点复杂。

**Comment by LanWong1** [comment]
> 我之后会加一个跑单张图的脚本，不过这几天有事，可能要下周，你可以先试试[这个](https://github.com/MhLiao/DB/issues/22#issuecomment-562018764)。我们做实验的时候尝试了很多设置和搭配，所以代码结构有点复杂。

谢谢大神，膜拜中

**Comment by curiosity2** [comment]
同感，代码结构太复杂了 参数怎么传的都搞不明白   我明明要跑eval却报没有训练数据的错误  :(
