### ISSUE TITLE
对td500-resnet50进行evaluate的时候指标几乎为0。

### ISSUE THREAD

**Issue by guangzufang** [MhLiao/DB#266]
用了训练好的模型，进行评估，指标几乎为0。ICDAR2015数据集用给定的模型和自己训练的模型F指标只有55左右，请问是什么问题？
![QQ图片20210606171823](https://user-images.githubusercontent.com/56466676/120919263-3a243e00-c6eb-11eb-90db-41bd6f2e6196.jpg)

**Comment by youzhaxiaomayi** [comment]
同问
![image](https://user-images.githubusercontent.com/15650823/124096220-f70c7f00-da8c-11eb-9e6e-85f720721b18.png)

**Comment by futureisatyourhand** [comment]
> 同问 ![image](https://user-images.githubusercontent.com/15650823/124096220-f70c7f00-da8c-11eb-9e6e-85f720721b18.png)

咋解决的！！感谢

**Comment by ming-eng** [comment]
老哥们，不加载预训练效果是不是很差

**Comment by happy20200** [comment]
> > 同问 ![image](https://user-images.githubusercontent.com/15650823/124096220-f70c7f00-da8c-11eb-9e6e-85f720721b18.png)
> 
> 咋解决的！！感谢

解决了吗，同问
