### ISSUE TITLE
百度网盘的数据集里没有images文件

### ISSUE THREAD

**Issue by 1996leo** [MhLiao/DB#27]
提供的datasets百度网盘链接里的total_text文件夹中没有train_images和test_images文件

**Comment by MhLiao** [comment]
为了避免版权纠纷以及缩短大部分人的下载时间，我没有把图片放上去，建议直接到数据集官方下载图片。

**Comment by 1996leo** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Minghui Liao"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 下午4:43
收件人:&nbsp;"MhLiao/DB"<DB@noreply.github.com&gt;;
抄送:&nbsp;"孙天磊"<1033789689@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MhLiao/DB] 百度网盘的数据集里没有images文件 (#27)




为了避免版权纠纷以及缩短大部分人的下载时间，我没有把图片放上去，建议直接到数据集官方下载图片。

**Comment by 1996leo** [comment]
> 为了避免版权纠纷以及缩短大部分人的下载时间，我没有把图片放上去，建议直接到数据集官方下载图片。

好的，谢谢

**Comment by CaiQiuYu** [comment]
> 为了避免版权纠纷以及缩短大部分人的下载时间，我没有把图片放上去，建议直接到数据集官方下载图片。

能否提供下数据集的连接呢

**Comment by MhLiao** [comment]
@CaiQiuYu Totaltext: https://github.com/cs-chan/Total-Text-Dataset
