### ISSUE TITLE
How can I generate or obtain the visualization result for predicted characters?

### ISSUE THREAD

**Issue by Peony-Wang** [MhLiao/DB#28]
Hi Minghui, thanks for your awesome work!

I found that adding --visulize after the evaluation command will generate the visualization results for only the threshold map. I'm wondering how  can I generate or obtain the visualization result for predicted characters? 

Thank you!

**Comment by MhLiao** [comment]
@Peony-Wang What's the meaning of predicted characters? Do you mean the recognition results? This repo is only a scene text detector which produces bounding boxes of the text instances.

**Comment by Peony-Wang** [comment]
> @Peony-Wang What's the meaning of predicted characters? Do you mean the recognition results? This repo is only a scene text detector which produces bounding boxes of the text instances.

Got it. Thanks for your reply! I have one more question, could you give a clue that how to combine your work with other detection+recognition work to improve the result of the  recognition result?

**Comment by MhLiao** [comment]
@Peony-Wang Once you get the detection results of our method, you can crop the text regions for recognition (eg. CRNN or ASTER).

**Comment by Peony-Wang** [comment]
Thank you for your answer！
