### ISSUE TITLE
问一个关于synthtext数据集的问题

### ISSUE THREAD

**Issue by moooood** [MhLiao/DB#29]
之前一直在用tensorflow，所以synthtext这个数据集的图片和标注都是处理成tfrecord的格式。这边用syntntext数据集进行训练的时候需要怎么处理呢？处理成一张图片img_name.jpg对应标注img_name.txt的形式吗？

**Comment by moooood** [comment]
还有 标注信息是处理成什么样的形式？4个值矩形框（左上角点，右下角点），还是8个值（多边形4个点）？

**Comment by MhLiao** [comment]
参考TD500和total-text的数据格式。SynthText我处理成了8个值（多边形4个点）。
