### ISSUE TITLE
运行demo.py也要提供数据集正确解决方法

### ISSUE THREAD

**Issue by futureflsl** [MhLiao/DB#296]
以DB/experiments/seg_detector/totaltext_resnet18_deform_thre.yaml为例子删除里面train,validation,logger,evaluation然后注释
demo.py第53行
        #model_saver = experiment.train.model_saver
经过测试发现没问题了，希望可以帮到大家

**Comment by yeruiqian** [comment]
> 以DB/experiments/seg_detector/totaltext_resnet18_deform_thre.yaml为例子删除里面train,validation,logger,evaluation然后注释 demo.py第53行 #model_saver = experiment.train.model_saver 经过测试发现没问题了，希望可以帮到大家

it works for me， thank you
