### ISSUE TITLE
学长的忠实粉丝，从textboxes，textboxes++一路跟来，盼望开源

### ISSUE THREAD

**Issue by moooood** [MhLiao/DB#3]

**Comment by MhLiao** [comment]
谢谢支持！

**Comment by deepseek** [comment]
@moooood close this issue, and let MhLiao focus on developing the code

**Comment by WenmuZhou** [comment]
期待开源，自己实现的无法收敛

**Comment by WangJie8682** [comment]
我也是自己实现的无法收敛，等大佬开源

**Comment by WenmuZhou** [comment]
@WangJie8682 bmap在进bce之前需要sigmoid，这样就可以收敛了，我的是这样，但是理论上bmap已经是sigmoid了的，很奇怪

**Comment by WangJie8682** [comment]
@WenmuZhou 我试试，大佬那边改了之后结果对吗

**Comment by WenmuZhou** [comment]
@WangJie8682 看起来是对的
