### ISSUE TITLE
为什么thresh_map的最小值要设置为0.3

### ISSUE THREAD

**Issue by WenmuZhou** [MhLiao/DB#30]
这一行为什么要设置canvas 的最小值是0.3？
https://github.com/MhLiao/DB/blob/master/data/processes/make_border_map.py#L41

**Comment by wanzysky** [comment]
事实上如代码表现出的，阈值的最小值和最大值是可以配置的参数。具体地，设置0.3和0.7作为阈值的最大值和最小值是参考了baseline上二值化的阈值，0.3到0.7之间会有比较好的表现。
