### ISSUE TITLE
train  error in modulated_deformable_col2im_coord_cuda

### ISSUE THREAD

**Issue by ssma96** [MhLiao/DB#31]
python train.py experiments/seg_detector/ic15_resnet50_deform_thre.yaml --num_gpus 4
[INFO] [2019-12-05 05:32:38,907] Training epoch 0
error in modulated_deformable_col2im_coord_cuda: invalid device function
error in modulated_deformable_col2im_cuda: invalid device function

**Comment by ssma96** [comment]
python train.py experiments/seg_detector/ic15_resnet50_deform_thre.yaml --num_gpus 4
[INFO] [2019-12-05 05:32:38,907] Training epoch 0
error in modulated_deformable_col2im_coord_cuda: invalid device function
error in modulated_deformable_col2im_cuda: invalid device function

**Comment by ssma96** [comment]
I have solved the problem using cuda_10.1
This error occurred using cuda_10.0
Thanks for sharing this awesome work

**Comment by DanLiu0623** [comment]
@cosen1024 请教下我换成cuda10.1编译dcn就出现问题了，如下图，cuda10.0编译没问题，但是训练有问题。
![Screenshot from 2021-04-15 15-20-04](https://user-images.githubusercontent.com/16029479/114829977-47fdc700-9dfe-11eb-9ad5-eb5b76838d7e.png)
