### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by HITerStudy** [MhLiao/DB#32]
Thanks for your excellent work! But I have a question, why I get the inconsistent results with the ones reported in paper when testing the fintuned resnet-18 backbone on TotalText?

**Comment by MhLiao** [comment]
@HITerStudy The models should achieve similar results as these in the paper. What're your results?

**Comment by HITerStudy** [comment]
Thanks for you reply, and I got the results(Precision:85.7 Recall:78.52 F1:81.9) on the totalText, but reported result is (Precision:88.3 Recall:77.9 F1: 82.8)?

**Comment by MhLiao** [comment]
@HITerStudy precision and recall are a trade-off. Thus, you can adjust the `box_thresh` to balance the precision and recall to get a better F-measure. Could you please try a value of 0.7 for the `box_thresh`?

**Comment by HITerStudy** [comment]
Thanks！I will have a try!

**Comment by MhLiao** [comment]
@HITerStudy I tried it with a `box_threshold` of 0.7 and the result is (precision: 0.888716, recall: 0.776221, F-measure: 0.828668)
