### ISSUE TITLE
Fine Tune?

### ISSUE THREAD

**Issue by zobeirraisi** [MhLiao/DB#34]
How to use the pre-trained model of SynthDat for finetuning? How to add this weight to `train.py` script?

**Comment by MhLiao** [comment]
@zobeirraisi Using `--resume model_path` in the training command.

**Comment by moooood** [comment]
Is the pretrained model "pre-trained-model-synthtext-resnet18" trained on synthtext dataset with dcn or normal conv2d?

**Comment by MhLiao** [comment]
@moooood It is trained with DCN.

**Comment by MhLiao** [comment]
@moooood It seems that I uploaded the wrong "pre-trained-model-synthtext-resnet18" which does not include the DCN.

**Comment by deepseek** [comment]
@MhLiao :sunglasses: 
in regards of F1, recall, precision, whats the difference between the dcn and normal conv2d version?
resnet 18 vs deformable resnet 18

**Comment by MhLiao** [comment]
@deepseek DCN usually achieves higher performance, especially for the long text lines, since DCN gives a more flexible receptive field for the backbone.

**Comment by liangkaihuan** [comment]
@MhLiao Could you provide the "pre-trained-model-synthtext-resnet18" model which trained with DCN?

**Comment by MhLiao** [comment]
@liangkaihuan I will provide the model but maybe I need to find it or re-train it.

**Comment by moooood** [comment]
The provided model ”pre-trained-model-synthtext-resnet18“ is trained with normal conv2d. Is that right？

**Comment by MhLiao** [comment]
> The provided model ”pre-trained-model-synthtext-resnet18“ is trained with normal conv2d. Is that right？

Yes. I will fix it later.

**Comment by shaohailin** [comment]
Is the pretrained model "**pre-trained-model-synthtext**" trained on synthtext dataset with dcn or normal conv2d now ? @MhLiao

**Comment by ZhengMengbin** [comment]
@shaohailin It was still pretrained with normal conv2d, you can print model.state_dict().keys().

**Comment by jeong-tae** [comment]
can anyone provide pretrained with DCN?

**Comment by lrjj** [comment]
> 您好，现在请问有DCN 预训练的pre-trained-model-synthtext-resnet18吗？
