### ISSUE TITLE
error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型

### ISSUE THREAD

**Issue by 1996leo** [MhLiao/DB#35]
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1502): error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1560): note: 参见对正在编译的类 模板 实例化“ska_ordered::order_preserving_flat_hash_map<K,V,H,E,A>”的引用
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1506): error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1514): error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1596): error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1633): note: 参见对正在编译的类 模板 实例化“ska_ordered::flat_hash_set<T,H,E,A>”的引用
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1601): error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1605): error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1609): error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型
D:/STL/software/Anaconda/Anaconda33/envs/DB/lib/site-packages/torch/include\c10/util/order_preserving_flat_hash_map.h(1613): error C3203: “templated_iterator”: 未专用化的 类 模板 不能用作 模板 变量，该变量属于 模板 参数“_Ty1”，应为 real 类型

**Comment by MhLiao** [comment]
@1996leo 你能使用Ubuntu系统吗？我没有测试过windows系统。
