### ISSUE TITLE
Do the text boundary boxes in annotation files have to be as close as possible to the text itself?

### ISSUE THREAD

**Issue by btminh1820** [MhLiao/DB#351]
I am transfer learning DB using my own custom dataset. However, the preannotations of the text instance boxes are not quite close to the text instance itself. I was wondering if it could affect the overall performance of DB?

**Comment by btminh1820** [comment]
For example from my text boundary annotation:
![test](https://user-images.githubusercontent.com/77532106/197477170-79a3679b-ffa3-4578-a3b1-a788993f8263.png)

**Comment by btminh1820** [comment]
@MhLiao

**Comment by suhas004** [comment]
Hey @btminh1820 
the bbox formation always takes in the post-processing step.
You can go to `structures -> representers -> seg_detector_representer.py` and search for `unclip_ratio` and you can adjust the ratio there. The higher the ratio, the boxes will have more area comparatively

**Comment by btminh1820** [comment]
@suhas004 Thanks for the greate advice!

**Comment by dahalsweekar** [comment]
@btminh1820 Please say how did you annotate your custom dataset?
