### ISSUE TITLE
deform_conv报错，是不是什么版本有问题？

### ISSUE THREAD

**Issue by g2dog** [MhLiao/DB#36]
![91c7d8a311a0712695b6cc566f6353df](https://user-images.githubusercontent.com/20312161/70298195-bf474200-182b-11ea-9e5e-dbff057234a6.jpg)

我用的redhat7.4，python3.6.2, gcc 4.9.2, Cython 0.28, torch 1.3，cuda 10.1，
 deformable convolution编译的时候没问题，已经生成文件了。
但是在运行eval.py进行测试时，报了图中的错误。我怀疑是哪个库版本不一致导致的，麻烦您有空看一下，谢谢

**Comment by g2dog** [comment]
![91c7d8a311a0712695b6cc566f6353df](https://user-images.githubusercontent.com/20312161/70298340-4eecf080-182c-11ea-9479-f9c14ea3c296.jpg)

**Comment by Sylvia6** [comment]
same problem...

**Comment by MhLiao** [comment]
有可能是编译使用的cuda的版本和pytorch的cuda版本不一致

**Comment by MhLiao** [comment]
Make sure your CUDA path of $CUDA_HOME is the same version as your CUDA in PyTorch by the command of `echo $CUDA_HOME`. If not, you need to change the `$CUDA_HOME` by `export CUDA_HOME=path-of-another-version' or re-install PyTorch with the same CUDA version as in `CUDA_HOME`.

**Comment by Sqrt5** [comment]
一样的问题，使用的conda安装的pytorch，cudatoolkit是10.0.130版本
<img width="306" alt="image" src="https://user-images.githubusercontent.com/3362836/70522151-8a185800-1b7b-11ea-8265-1c8c0cd2f03e.png">
cuda装的也是10.0.130
<img width="162" alt="image" src="https://user-images.githubusercontent.com/3362836/70522221-afa56180-1b7b-11ea-97cc-513740601d4d.png">
python:3.6.5
pytorch:1.2.0
torchvision:0.4.0
cudatoolkit:10.0.130-0
cuda:10.0.130
cudnn:7.6.4
难道说10.0.130-0和10.0.130还不一样吗
进入到那个目录直接import，返回如下错误
<img width="643" alt="image" src="https://user-images.githubusercontent.com/3362836/70522412-0874fa00-1b7c-11ea-8b4c-352ee4f60470.png">

**Comment by g2dog** [comment]
多谢多谢，问题找到了，是第一次gcc版本不对，编译失败，没删掉build文件夹，虽然第二次升级完gcc编译成功了，但是运行的时候报错了。
删掉了build文件夹，重新编译下，问题解决了。

**Comment by Sqrt5** [comment]
> 多谢多谢，问题找到了，是第一次gcc版本不对，编译失败，没删掉build文件夹，虽然第二次升级完gcc编译成功了，但是运行的时候报错了。
> 删掉了build文件夹，重新编译下，问题解决了。

升级到4.9.2解决的吗？

**Comment by Sqrt5** [comment]
问题稀里糊涂解决的，操作如下
升级gcc到4.9.2
卸载cuda10.0再重装cuda10.0
用conda卸载安装的torch/torchvision/cudatoolkit
用pip安装torch==1.2.0/torchvision==0.4.0
然后目前是不报编译的错了

**Comment by g2dog** [comment]
> > 多谢多谢，问题找到了，是第一次gcc版本不对，编译失败，没删掉build文件夹，虽然第二次升级完gcc编译成功了，但是运行的时候报错了。
> > 删掉了build文件夹，重新编译下，问题解决了。
> 
> 升级到4.9.2解决的吗？

解决了，我用的torch1.3, gcc4.9.2，cuda10.1
