### ISSUE TITLE
测试结果跟论文相差很大

### ISSUE THREAD

**Issue by corleonechensiyu** [MhLiao/DB#39]
![2019-12-06 17-52-23屏幕截图](https://user-images.githubusercontent.com/39826330/70314316-3099eb80-1852-11ea-87d1-17591be2c8f5.png)
![2019-12-06 17-52-55屏幕截图](https://user-images.githubusercontent.com/39826330/70314318-3099eb80-1852-11ea-9556-2d146d3bd0aa.png)
![2019-12-06 17-55-55屏幕截图](https://user-images.githubusercontent.com/39826330/70314319-31328200-1852-11ea-977c-f1c4881a78bb.png)

**Comment by MhLiao** [comment]
@corleonechensiyu 请先阅读说明文档，并明确以下四点：
1. 应使用对应数据集训练的模型去测试该模型，比如用total-text的模型去测total-text，而不是用total-text的模型去测ICDAR2015。
2. 应检查图片的输入尺寸是否与论文中一致。
3. 如果结果中的F-measure跟论文中不一样，但是precision和recall相比论文一个更高一个更低，应该调整`box_thresh`。因为precision和recall是一个tradeoff。
4. 测试速度的时候请使用`--speed`参数，否则测到的速度将不准确，大部分是IO的耗时。

**Comment by corleonechensiyu** [comment]
嗯嗯，不好意思，后面发现测试的模型没有icdar2015的，一时糊涂

**Comment by Xuanmeng-Zhang** [comment]
> @corleonechensiyu 请先阅读说明文档，并明确以下四点：
> 
> 1. 应使用对应数据集训练的模型去测试该模型，比如用total-text的模型去测total-text，而不是用total-text的模型去测ICDAR2015。
> 2. 应检查图片的输入尺寸是否与论文中一致。
> 3. 如果结果中的F-measure跟论文中不一样，但是precision和recall相比论文一个更高一个更低，应该调整`box_thresh`。因为precision和recall是一个tradeoff。
> 4. 测试速度的时候请使用`--speed`参数，否则测到的速度将不准确，大部分是IO的耗时。

你好, 对于结果中的F-measure跟论文中不一样，可否给出一下作者您对代码给出的数据集对应模型的box_thresh的值呢？

**Comment by shaohailin** [comment]
I make the base_icdar2015.yaml and icdar2015_resnet50_deform_thre.yaml by referencing base_totaltext.yaml and totaltext_resnet50_deform_thre.yaml.Changes are there:
![图片](https://user-images.githubusercontent.com/56865153/71607007-e554cd80-2bb0-11ea-8760-a0b6ec95fe54.png)
![图片](https://user-images.githubusercontent.com/56865153/71607017-fa316100-2bb0-11ea-9b2d-5b3a73dc442b.png)
This is my training command:
CUDA_VISIBLE_DEVICES=4,5 python train.py experiments/seg_detector/icdar2015_resnet50_deform_thre.yaml --resume Models/pre-trained-model-synthtext-resnet50 --num_gpus 2
This is my testing command and result:
![图片](https://user-images.githubusercontent.com/56865153/71607195-36b18c80-2bb2-11ea-90f0-dc6b059aecc5.png)
You can see that the result is far lower than your result in paper, could you give me some advice to reach your result?
your result:
![图片](https://user-images.githubusercontent.com/56865153/71607471-c6583a80-2bb4-11ea-9845-22dc0ad10da4.png)

one more question:
When will you release the right pre-trained-model-synthtext-resnet18 model model trained with DCN?
@corleonechensiyu @MhLiao

**Comment by shaohailin** [comment]
![图片](https://user-images.githubusercontent.com/56865153/71947179-064b9d00-3207-11ea-8743-4d7d046abadb.png)
你的在icdar2015上的结果是多少？我基于resnet50预训练的情况下，size1152,结果与作者的相差太大
@MhLiao @corleonechensiyu
