### ISSUE TITLE
paper typo

### ISSUE THREAD

**Issue by opconty** [MhLiao/DB#4]
page 7 table 5: CDAFT (Baek et al. 2019) 89.8 84.3 86.9 may be CRAFT

**Comment by deepseek** [comment]
yup i saw it too, they surely meant CRAFT

**Comment by deepseek** [comment]
@opconty by the way, any updates regarding `keras_std_plus_plus`?

**Comment by MhLiao** [comment]
@opconty You are right. Thanks for your reminder.

**Comment by opconty** [comment]
> @opconty You are right. Thanks for your reminder.

My pleasure

**Comment by opconty** [comment]
> @opconty by the way, any updates regarding `keras_std_plus_plus`?

I am still working on that, thanks for your attention
