### ISSUE TITLE
请问adaptive 这个参数是什么意思啊？

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#41]
![image](https://user-images.githubusercontent.com/33218397/70416577-5a455380-1a9a-11ea-8ee4-1fbf9584a00e.png)
您好 请问这个参数是什么意思 训练的时候需要开着吗

**Comment by MhLiao** [comment]
@LanWong1 这个参数控制着是否使用DB，训练的时候应该开着。

**Comment by LanWong1** [comment]
谢谢！
