### ISSUE TITLE
KeyError: 'Experiment'

### ISSUE THREAD

**Issue by Xuanmeng-Zhang** [MhLiao/DB#43]
Dear author, I wanted to train the model with command "python train.py experiments/seg_detector/base_totaltext.yaml --num_gpus 8", and the error raise that
  File "train.py", line 72, in <module>
    main()
  File "train.py", line 62, in main
    experiment_args = conf.compile(conf.load(args['exp']))['Experiment']
KeyError: 'Experiment'

How can I solve these problem?

**Comment by MhLiao** [comment]
@Xuanmeng-Zhang Please see the claim [here](https://github.com/MhLiao/DB/blob/master/README.md#config-file)
