### ISSUE TITLE
yaml文件里参数的意义

### ISSUE THREAD

**Issue by 09876qwrte** [MhLiao/DB#44]
你好，我看到yaml文件里有很多参数，不太清楚某些参数的具体意义，请问你什么时候有时间可以给我们解释一下这些参数的用处吗

**Comment by MhLiao** [comment]
现在的参数确实有些冗余，我之后会重新组织和精简这些参数，并加上注释。

**Comment by 09876qwrte** [comment]
好的，谢谢，期待你后续的工作
