### ISSUE TITLE
可视化的图变得模糊

### ISSUE THREAD

**Issue by rkshuai** [MhLiao/DB#45]
请问为什么使用参数--visualize后得到的可视化图很模糊？
![img95 jpg_output](https://user-images.githubusercontent.com/11296462/70443575-5aae1080-1ad3-11ea-8489-1b9cf75454c9.jpg)

**Comment by rkshuai** [comment]
@MhLiao 能帮忙解答一下吗

**Comment by MhLiao** [comment]
@rkshuai 因为图片经过了两次resize而且是从numpy转成tensor减了均值，再还原回来的。如果要高清图可以直接读原始图片进行可视化，参考demo.py中的可视化。

**Comment by shaohailin** [comment]
你解决这个问题了吗？能不能告诉我该怎么解决这个问题？ @rkshuai @MhLiao
