### ISSUE TITLE
forward() missing 1 required positional argument: 'data'

### ISSUE THREAD

**Issue by SimonsXuan** [MhLiao/DB#46]
I find this error when I run eval.py and demo.py, it seemed something went wrong with the data input?
 File "eval.py", line 194, in <module>
    main()
  File "eval.py", line 80, in main
    Eval(experiment, experiment_args, cmd=args, verbose=args['verbose']).eval(args['visualize'])
  File "eval.py", line 177, in eval
    pred = model.forward(batch, training=False)
  File "/ssd/xmzhang/TextDetection/lab1/DB/structure/model.py", line 56, in forward
    pred = self.model(data, training=self.training)

TypeError: forward() missing 1 required positional argument: 'data'

**Comment by deepseek** [comment]
@MhLiao This issue is a replicate of #17 
please close it

**Comment by 09876qwrte** [comment]
I set os.envriron["CUDA_VISILIB_DEVICES"] to solve this problem

**Comment by deepseek** [comment]
yes, example:
```
CUDA_VISIBLE_DEVICES=0 python eval.py experiments/seg_detector/totaltext_resnet18_deform_thre.yaml --resume ./models/totaltext_resnet18 --polygon --box_thresh 0.6
```

**Comment by Xuanmeng-Zhang** [comment]
Thank you, it works. But still have a question, I added the code 
`os.environ['CUDA_VISIBLE_DEVICES'] = '0' in the eval.py， but it didn' t word.

**Comment by wangning7149** [comment]
> I find this error when I run eval.py and demo.py, it seemed something went wrong with the data input?
> File "eval.py", line 194, in 
> main()
> File "eval.py", line 80, in main
> Eval(experiment, experiment_args, cmd=args, verbose=args['verbose']).eval(args['visualize'])
> File "eval.py", line 177, in eval
> pred = model.forward(batch, training=False)
> File "/ssd/xmzhang/TextDetection/lab1/DB/structure/model.py", line 56, in forward
> pred = self.model(data, training=self.training)
> TypeError: forward() missing 1 required positional argument: 'data'

我是在训练的时候遇到这个问题的，指定一个gpu也没用，请问怎么解决？
