### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by zjuzxm** [MhLiao/DB#47]
When training the model with totaltext, I got this error when running the command
` python mytrain.py experiments/seg_detector/totaltext_resnet18_deform_thre.yaml --num_gpus 4 `. Can you help me? Thank you!

`libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0`
`Traceback (most recent call last):
  File "train.py", line 72, in <module>
    main()
  File "train.py", line 69, in main
    trainer.train()
  File "/DB/trainer.py", line 86, in train
    epoch=epoch, step=self.steps)
  File "/DB/trainer.py", line 127, in train_step
    if step % self.experiment.logger.log_interval == 0:
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'`

**Comment by MhLiao** [comment]
@zjuzxm That's a bug after I added a demo script. I fixed it with [this commit](https://github.com/MhLiao/DB/commit/c26bc87c0f1688b9a10e7cc054ff1b541ee3628f).
