### ISSUE TITLE
模型鲁棒性似乎不太好

### ISSUE THREAD

**Issue by ws-lin** [MhLiao/DB#48]
请问博主，模型对中文检测是不是效果比较差，而且容易把二维码的纹理识别成字，我用demo.py测试一些电商图片效果很差

**Comment by MhLiao** [comment]
@ws-lin 训练数据里没有电商图片也没有中文，而且总共才小几百张训练图片，不重新训练效果不会好的。相对其他类型的方法来说，基于分割的文本检测方法的泛化性能和鲁棒性是比较好的了。

**Comment by ws-lin** [comment]
嗯嗯，谢谢博主的解答
