### ISSUE TITLE
The training time

### ISSUE THREAD

**Issue by Xuanmeng-Zhang** [MhLiao/DB#49]
Dear author, Could you give me the information about your training time and your computing resource?
I found it cost about 50min with 4 Titian Xp GPUs to train one epoch. Is it normal ?

**Comment by MhLiao** [comment]
@Xuanmeng-Zhang The training time of one epoch is highly related to the number of training images. If the number of your training images are much larger than 1000, you should shorten the training epochs. Take Total-Text (about 1200 images) as an example, It takes about 1~2 minutes for one epoch (78 iters) with Titan Xp GPUs.  Thus, the training speed is about 1~2 seconds/iter.
