### ISSUE TITLE
 inference的输出是什么？

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#54]
请问代码里的模型输出pred是 probability map 还是 the approximate binary map？
还有从代码看，得到文字区域的步骤并不是按照论文里的方法三步走的？
![图片](https://user-images.githubusercontent.com/33218397/70603333-497b1600-1c31-11ea-80bb-c200fdf1769c.png)

**Comment by MhLiao** [comment]
@LanWong1 是probability map

**Comment by LanWong1** [comment]
谢谢
