### ISSUE TITLE
每次跑demo结果结果不一样

### ISSUE THREAD

**Issue by lillyPJ** [MhLiao/DB#55]
1. 代码、输入等完全一样
2. 结果不一致（不确定性会出现哪个结果）
（1）结果一：
python demo.py experiments/seg_detector/totaltext_resnet18_deform_thre.yaml --image_path ./datasets/total_text/test_images/img1000.jpg  --resume ./models/totaltext_resnet18     --polygon --box_thresh 0.2 --visualiz
verbose: True
Initializing log dir for workspace/SegDetectorModel-seg_detector/deformable_resnet18/L1BalanceCELoss
./datasets/total_text/
Resuming from ./models/totaltext_resnet18
Resumed from ./models/totaltext_resnet18
Traceback (most recent call last):
  File "demo.py", line 148, in <module>
    main()
  File "demo.py", line 43, in main
    Demo(experiment, experiment_args, cmd=args).inference(args['image_path'], args['visualize'])
  File "demo.py", line 138, in inference
    output = self.structure.representer.represent(batch, pred, is_output_polygon=self.args['polygon'])
  File "/project/DB/structure/representers/seg_detector_representer.py", line 53, in represent
    segmentation[batch_index], width, height)
  File "/project/DB/structure/representers/seg_detector_representer.py", line 102, in polygons_from_bitmap
    _, sside = self.get_mini_boxes(box.reshape((-1, 1, 2)))
  File "/project/DB/structure/representers/seg_detector_representer.py", line 171, in get_mini_boxes
    bounding_box = cv2.minAreaRect(contour)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/convhull.cpp:137: error: (-215:Assertion failed) total >= 0 && (depth == CV_32F || depth == CV_32S) in function 'convexHull'

（2）结果二：
verbose: True
Initializing log dir for workspace/SegDetectorModel-seg_detector/deformable_resnet18/L1BalanceCELoss
./datasets/total_text/
Resuming from ./models/totaltext_resnet18
Resumed from ./models/totaltext_resnet18
程序没error，但跑出来结果完全空的，降低阈值为0.2后有输出，但是框都是在图像的最下面一行（高度为1，紧贴下边线）。
3. 不知道是不是环境问题？
CUDA = 10.0，CUDA_DRIVER = 410.48
Package                Version
---------------------- -----------
anyconfig              0.9.10
Click                  7.0
cycler                 0.10.0
decorator              4.4.1
editdistance           0.5.3
Flask                  1.1.1
gevent                 1.4.0
gevent-websocket       0.10.1
greenlet               0.4.15
imageio                2.6.1
imgaug                 0.3.0
itsdangerous           1.1.0
Jinja2                 2.10.3
kiwisolver             1.1.0
MarkupSafe             1.1.1
matplotlib             3.1.2
munch                  2.5.0
networkx               2.4
numpy                  1.17.4
opencv-python          4.1.2.30
opencv-python-headless 4.1.2.30
Pillow                 6.2.1
pip                    19.3.1
protobuf               3.11.1
pyclipper              1.1.0.post3
pyparsing              2.4.5
python-dateutil        2.8.1
PyWavelets             1.1.1
PyYAML                 5.2
scikit-image           0.16.2
scipy                  1.3.3
setuptools             42.0.2
Shapely                1.6.4.post2
six                    1.13.0
sortedcontainers       2.1.0
tensorboardX           1.9
torch                  1.2.0
torchvision            0.4.0
tqdm                   4.40.2
Werkzeug               0.16.0
wheel                  0.33.6

**Comment by MhLiao** [comment]
@lillyPJ 因为模型的输出是乱的所以后处理才会报错。请问你是否有改动yaml文件？我怀疑是config文件和模型不匹配，比如一个用了dcn一个没用。

**Comment by lillyPJ** [comment]
没改过

**Comment by lillyPJ** [comment]
出现结果不确定是因为什么原因？即使输出是乱的，也应该是确定的值？

**Comment by lillyPJ** [comment]
验证了：如果是多gpu，会出现这个问题，即使跑通结果也有问题。只使用单GPU（export CUDA_VISIBLE_DEVICES="1"），可以跑通正确结果。

**Comment by wuzuowuyou** [comment]
> export CUDA_VISIBLE_DEVICES="1"

单GPU不是应该是0吗？  export CUDA_VISIBLE_DEVICES="0"
我也遇到这个问题

**Comment by northeastsquare** [comment]
@wuzuowuyou  0 表示第0块GPU, 1 表示第一块GPU, 单GPU可以指定任何一个GPU
