### ISSUE TITLE
My result on total_text/test_images/img10.jpg is null

### ISSUE THREAD

**Issue by moooood** [MhLiao/DB#56]

**Comment by moooood** [comment]
the same script as author in readme.md

**Comment by moooood** [comment]
empty res_img10.txt and clean img10.jpg

**Comment by lillyPJ** [comment]
same

**Comment by MhLiao** [comment]
@moooood It works for me. I suggest you check the model and the config file to make sure that they are match to each other. Have you changed the DCN setting in the config file?

**Comment by MhLiao** [comment]
@moooood Maybe you should use CUDA_VISIBLE_DEVICES=gpu_index. see [here](https://github.com/MhLiao/DB/issues/55).

**Comment by moooood** [comment]
> @moooood It works for me. I suggest you check the model and the config file to make sure that they match each other. Have you changed the DCN setting in the config file?

I didn't change the corresponding ymal file.

**Comment by moooood** [comment]
@MhLiao I didn't change the corresponding ymal file.

**Comment by moooood** [comment]
@MhLiao I solve my problem under your guide.Thank you.

**Comment by shaohailin** [comment]
could you sent me the link of total_text dataset? @moooood

**Comment by moooood** [comment]
@shaohailin You can find total-text repository in github. You can also download dataset via https://drive.google.com/file/d/1bC68CzsSVTusZVvOkk7imSZSbgD1MqK2/view?usp=sharing.
