### ISSUE TITLE
box thresh的设置

### ISSUE THREAD

**Issue by Xuanmeng-Zhang** [MhLiao/DB#57]
你好, 对于结果中的F-measure跟论文中不一样，可否给出一下作者您对代码给出的数据集对应模型的box_thresh的值呢？

**Comment by MhLiao** [comment]
@Xuanmeng-Zhang 对应结果已更新在README中。注意base_td500.yaml中的默认尺度现在已改为736，方便复现结果。

**Comment by Xuanmeng-Zhang** [comment]
我刚刚按照readme测试了下total_text, res18和res50的fmeasure都比论文中给的低一个百分点。
`  CUDA_VISIBLE_DEVICES=0 python eval.py experiments/seg_detector/totaltext_resnet18_deform_thre.yaml --resume ./models/totaltext_resnet18 --polygon --box_thresh 0.7
./datasets/total_text/
[INFO] [2019-12-11 13:17:44,966] Resuming from ./models/totaltext_resnet18
[INFO] [2019-12-11 13:17:45,035] Resumed from ./models/totaltext_resnet18
 72%|██████████████████████████████████████████████████████████████████████▏                          | 217/300 [00:24<00:06, 12.84it/s 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:32<00:00,  9.22it/s][INFO] [2019-12-11 13:18:18,542] precision : 0.879543 (300)
[INFO] [2019-12-11 13:18:18,543] recall : 0.765823 (300)
[INFO] [2019-12-11 13:18:18,544] fmeasure : 0.818753 (1) `

`  CUDA_VISIBLE_DEVICES=0 python eval.py experiments/seg_detector/totaltext_resnet50_deform_thre.yaml --resume ./models/totaltext_resnet50 --polygon --box_thresh 0.6
./datasets/total_text/
[INFO] [2019-12-11 13:15:51,805] Resuming from ./models/totaltext_resnet50
[INFO] [2019-12-11 13:15:52,067] Resumed from ./models/totaltext_resnet50
 75%|████████████████████████████████████████████████████████████████████████▊                        | 225/300 [00:31<00:11,  6.72it/s 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:42<00:00,  7.04it/s][INFO] [2019-12-11 13:16:35,678] precision : 0.869990 (300)
[INFO] [2019-12-11 13:16:35,682] recall : 0.804702 (300)
[INFO] [2019-12-11 13:16:35,684] fmeasure : 0.836073 (1) `

**Comment by MhLiao** [comment]
@Xuanmeng-Zhang 下面是我的结果：
![image](https://user-images.githubusercontent.com/21288480/70625589-aab8de80-1c5d-11ea-8bd1-20693d694bff.png)

![image](https://user-images.githubusercontent.com/21288480/70625559-996fd200-1c5d-11ea-84f0-0f51cc7bd6b1.png)

**Comment by Xuanmeng-Zhang** [comment]
我试了好几次，结果依然是这样欸，有没有可能是模型上传错了？
![O6C(9Q~7NV8$E7TQYL{MS32](https://user-images.githubusercontent.com/58422832/70627201-bd80e280-1c60-11ea-98a0-4fbcea2d82a6.png)

**Comment by SimonsXuan** [comment]
@MhLiao 我eval的结果也要小一点，google drive的模型是服务器上这个吗？

**Comment by MhLiao** [comment]
@Xuanmeng-Zhang @SimonsXuan 我测了一下google drive的模型，跟我本地的模型表现一致，模型应该没问题。我突然想起来了，img651.jpg有exif信息，代码读取之后图像是旋转了90度的，需要先处理一下那张图。你们可以看一下那张图的可视化结果是不是有问题。

**Comment by Xuanmeng-Zhang** [comment]
@MhLiao 的确是Img651的问题，旋转之后的fmeasture就正确了，和您的结果是一样的。但另一个问题就是这个模型是训练1200个epoch得到的吗，我这里测得的final的模型正确率是这样的
<img width="636" alt="fa" src="https://user-images.githubusercontent.com/58422832/70674671-afaf7980-1cc1-11ea-9bde-7fa08d43bac3.png">

**Comment by MhLiao** [comment]
@Xuanmeng-Zhang 我的模型是用的1200 epoch的final，不过当时做实验用的两张卡训练的。卡的数量可能会对BN有影响。你试试两卡训练？

**Comment by Xuanmeng-Zhang** [comment]
感谢作者耐心解答，感觉可能是没有dcn的问题，带dcn的模型被误删了是说[https://download.pytorch.org/models/resnet18-5c106cde.pth](url)这个吗？如果是的话在哪里可以下载得到呢？作者能上传到google drive吗

**Comment by MhLiao** [comment]
@Xuanmeng-Zhang 不是，是指我提供的SynthText pre-train的模型。你训练的时候没有使用SynthText pretrain的模型吗？

**Comment by Xuanmeng-Zhang** [comment]
这样，我重新试一试，训练的时候的确没有使用预训练的模型。

**Comment by moooood** [comment]
哈哈 说出来你可能不信 我之前一直希望不用dcn 没想到学长正好放出来一个pre-train的模型没有使用dcn训练

**Comment by Xuanmeng-Zhang** [comment]
@MhLiao res18使用了pretrained的model后f-measure为81.9, res50使用pretrain的model是84.3, 所以，问题应当是没有dcn的问题。

**Comment by xxxxxxxiao** [comment]
你好！请问能不能提供下没用dcn的pre-train的模型？想试试看效果。谢谢

**Comment by xisi789** [comment]
> @MhLiao res18使用了pretrained的model后f-measure为81.9, res50使用pretrain的model是84.3, 所以，问题应当是没有dcn的
请问pretrained模型如何使用啊，我没有看到控制是否使用pretrain 的参数
