### ISSUE TITLE
跑SynthText遇到了OOM

### ISSUE THREAD

**Issue by WenmuZhou** [MhLiao/DB#58]
您好，感谢您的开源工作，我在跑SynthText数据集的时候，随着迭代次数的变多，cpu内存会一点点增长，最终撑爆了300G内存的服务器，请问您训练的时候遇到过吗，有没有什么解决办法可以提供一下？

**Comment by wanzysky** [comment]
能提供一下运行的命令和yaml文件吗

**Comment by WenmuZhou** [comment]
@wanzysky 我跑的不是这个仓库的代码，我把这个仓库的代码进行了修改，改成了适合我的结构，地址在这里https://github.com/WenmuZhou/DBNet.pytorch，
把[这里](https://github.com/WenmuZhou/DBNet.pytorch/blob/master/singlel_gpu_train.sh#L1)的配置文件改成SynthText_resnet18_FPN_DBhead_polyLR.yaml就可以了

**Comment by wanzysky** [comment]
抱歉我们无法支持debug其他repo的代码。
我们在使用这份代码pretrain的时候没有遇到持续的内存增长，建议检查一下实现的data loader。如果有具体的问题也欢迎讨论。

**Comment by WenmuZhou** [comment]
那我在这个repo里测试synthtext应该使用哪个dataset呢

**Comment by wanzysky** [comment]
[将SynthText处理成同样的格式即可，如果文件数量太多可以使用MegReader的[LMDB Dataset](https://github.com/Megvii-CSG/MegReader/blob/master/data/lmdb_dataset.py)

**Comment by WenmuZhou** [comment]
已经接近了，是深浅拷贝的问题，谢谢
