### ISSUE TITLE
只能创建GPU的模型？

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#59]
![图片](https://user-images.githubusercontent.com/33218397/70693722-fe2c3a80-1cf8-11ea-85fe-2a8b562979e8.png)

![图片](https://user-images.githubusercontent.com/33218397/70693845-392e6e00-1cf9-11ea-8508-bbdcb5f95b27.png)
![图片](https://user-images.githubusercontent.com/33218397/70693947-72ff7480-1cf9-11ea-9b79-1a130f486215.png)

在运行demo的时候，我选择了cpu，但是还是提示gpu内存不足，这是为什么呢？我看创建模型的时候使用nn.DataParallel，这个是不是只能使用GPU？

**Comment by LanWong1** [comment]
os.environ["CUDA_VISIBLE_DEVICES"] = "0" 解决了 需要添加这个

**Comment by cloudfool** [comment]
@LanWong1 请问您只改了上面提到的地方，就实现了cpu推理么？
