### ISSUE TITLE
Failed to build geventwebsocket

### ISSUE THREAD

**Issue by deepseek** [MhLiao/DB#6]
`pip install -r requirement.txt`
```
ERROR: Failed building wheel for geventwebsocket
```
Maybe you want to replace `geventwebsocket`, because it is failing to build.

**Comment by Mmmoran** [comment]
use commond pip install gevent-websocket

**Comment by deepseek** [comment]
I already did, this me telling the developer to change the requirements.txt

**Comment by MhLiao** [comment]
@deepseek @Mmmoran Thank you! I have changed the `requirements.txt`.
