### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ChaseMonsterAway** [MhLiao/DB#60]
1. 设置参数为smooth时的输出大小不匹配，threshold_conv最后一个1x1的卷积层的padding应该设置为0
2. test的时候，“字体大小小于7的忽略”这一步骤是否应该省略？
3. 当设置多卡训练的时候，使用--validate参数会报错，验证/测试的时候只能使用单卡

**Comment by ChaseMonsterAway** [comment]
另外经过测试，pytorch 1.1.0 torchvison 0.2.1 cuda 9.0的配置是可以的

**Comment by CXinXinGo** [comment]
> 
> 
> 另外经过测试，pytorch 1.1.0 torchvison 0.2.1 cuda 9.0的配置是可以的

请问pytorch 1.1.0 torchvison 0.2.1 cuda 9.0的配置是怎么测试的，谢谢

**Comment by ChaseMonsterAway** [comment]
> > 另外经过测试，pytorch 1.1.0 torchvison 0.2.1 cuda 9.0的配置是可以的
> 
> 请问pytorch 1.1.0 torchvison 0.2.1 cuda 9.0的配置是怎么测试的，谢谢

直接搭建环境测试啊
