### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by Sylvia6** [MhLiao/DB#61]
更换了icdar2019mlt数据集，训练的时候有些图片ok，但有会报错的:
![2019-12-12 20-05-15 的屏幕截图](https://user-images.githubusercontent.com/32163681/70710925-3e9cb000-1d1b-11ea-8be1-857e93ecdf08.png)

**Comment by Sylvia6** [comment]
![2019-12-12 20-05-15 的屏幕截图](https://user-images.githubusercontent.com/32163681/70710830-0eeda800-1d1b-11ea-9df3-c80d6b2f559e.png)

**Comment by rogerxsj** [comment]
可能是gt和img不配对，最好检查一下，我遇到过你这个情况，是数据集的问题。

**Comment by MhLiao** [comment]
@Sylvia6 这种错误可能是图片文件有问题或者路径有问题。
