### ISSUE TITLE
训练样本的点的方向必须是一致的吗？可以同时存在顺时针与逆时针的标注样本吗？

### ISSUE THREAD

**Issue by wuyunxiangwyx** [MhLiao/DB#62]

**Comment by LanWong1** [comment]
只跟区域有关系吧，点的顺序应该没有关系。

**Comment by hhhoushiyu** [comment]
请问gt.txt里的参数含义是什么？是一对横纵坐标吗？

**Comment by LanWong1** [comment]
是的 xy坐标




祝好！
王毅
在2019年12月13日 18:45，Joy 写道：

请问gt.txt里的参数含义是什么？是一对横纵坐标吗？

**Comment by LanWong1** [comment]
不同数据集不一样 有的数据集是polygon。totaltext是八个点的好像 icdra是4个点 矩形




祝好！
王毅
在2019年12月13日 18:46，LanWong1 写道：
是的 xy坐标




祝好！
王毅
在2019年12月13日 18:45，Joy 写道：

请问gt.txt里的参数含义是什么？是一对横纵坐标吗？

**Comment by moooood** [comment]
@LanWong1 准确地说 totaltext是4个点8个坐标值，Icdar是2个点，4个坐标值吧。

**Comment by MhLiao** [comment]
@wuyunxiangwyx 请尽量保证gt是顺时针，因为很多库在处理polygon的时候可能对点的顺序有要求，我不保证代码有对这种情况做过严格的转化。
