### ISSUE TITLE
为什么速度会快？

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#63]
为什么这个速度会比pse提升这么多呢，pse主要是在后处理部分耽误时间吗？模型大小好像跟pse差不多啊。但是pse后处理那部分使用c++写的，大概几百毫秒啊，为什么DB这个速度这么快？

**Comment by wanzysky** [comment]
是的。与PSENet和SAE对比，我们更注重通过把二值化融合到训练过程中以提升segmentation的效果，因此不需要复杂的后处理，从而不会造成测试速度的下降。
