### ISSUE TITLE
threshhold的监督和无监督是指什么意思？

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#64]
![图片](https://user-images.githubusercontent.com/33218397/70784562-a78c3280-1dc4-11ea-9135-14a9f93695cc.png)

**Comment by wanzysky** [comment]
Threshold map本身可以在没有监督的情况下学到。通过可视化地观察，我们发现threshold map会highlight文字区域的边缘。因此我们可以利用文字区域的标注对threshold进行监督以获得更好的效果。在论文中的Methodology和Ablation study两节都对此有讨论。
