### ISSUE TITLE
速度问题

### ISSUE THREAD

**Issue by lxsrepo** [MhLiao/DB#65]
请问一下速度问题
我尝试复现了一下，inference time约16~20ms 但数据从gpu导出到cpu需要10ms以上
在batch 为一的情况下，FPS不太可能达到50以上

论文里面说 inference time cost = forward time cost + post-processing time cost
所以 FPS = 1/inference-time 吗？
FPS定义不是每秒处理帧数吗？

**Comment by wanzysky** [comment]
请问“数据从gpu导出到cpu”具体是指什么过程，输入图片的分辨率是多少呢？

在我们的实验中如果是把分割图从GPU传到CPU，耗时应当是在1~2ms以内。

**Comment by lxsrepo** [comment]
操作
gpu_to_cpu_time=time.time()
probability_map=probability_map.cpu()
gpu_to_cpu_time=(time.time()-gpu_to_cpu_time)*1000
耗时10~30ms
probability_map    shape:(736,960~1xxx)
gpu: p40 
cpu: e5v4 主频2.4G
内存: ECC 速度 2400 MHz

**Comment by lxsrepo** [comment]
操作
gpu_to_cpu_time=time.time()
probability_map=probability_map.cpu()
gpu_to_cpu_time=(time.time()-gpu_to_cpu_time)*1000
耗时10-30ms
probability_map shape:(736,960-1xxx)
gpu: p40
cpu: e5v4 主频2.4G
内存: ECC 速度 2400 MHz

**Comment by lxsrepo** [comment]
输出示例
probability_map : torch.Size([1, 1, 960, 736])
index:5 img.shape:(960, 736, 3) forward_time:18.11ms      gpu_to_cpu_time:14.92ms   expand_time:5.15ms        end_time:38.21ms

**Comment by lxsrepo** [comment]
是我这边实现的问题，谢谢解答
