### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by shaohailin** [MhLiao/DB#67]
![图片](https://user-images.githubusercontent.com/56865153/70861950-4903b780-1f70-11ea-819e-df63971d2061.png)

i run the command without '--resume Models/pre-trained-model-synthtext-resnet50',It works.
But when i run the command 'CUDA_VISIBLE_DEVICES=5 python train.py experiments/seg_detector/totaltext_resnet50_deform_thre.yaml --resume Models/pre-trained-model-synthtext-resnet50 --num_gpus 1'. Errors shows 
![图片](https://user-images.githubusercontent.com/56865153/70862156-95042b80-1f73-11ea-8b96-db3dd74b205d.png)
![图片](https://user-images.githubusercontent.com/56865153/70862166-af3e0980-1f73-11ea-940e-da226763a559.png)

could anyone tell me how to solve it?

**Comment by MhLiao** [comment]
@shaohailin Your GPU memory is not enough for the ResNet-50 backbone with a single GPU. You can use two or more GPUs, or reduce the batch size.

**Comment by spoorgholi74** [comment]
You need to change the self.logger to logger in the Checkpointclass.
