### ISSUE TITLE
Seem like the network can't detect long text.

### ISSUE THREAD

**Issue by anhle-uet** [MhLiao/DB#68]

**Comment by MhLiao** [comment]
It can detect long text. Please see the result of the MSRA-TD500 dataset.

**Comment by moooood** [comment]
Does model rely on dcn to detect long text?

**Comment by MhLiao** [comment]
@moooood DCN is helpful and the segmentation-based method itself is friendly to detecting long text.

**Comment by moooood** [comment]
I train the model (Resnet18 without dcn) on my own dataset, it gets the Recall about 74%. I check the visual result, the trained model almost dismissed all the long text, e.g. 'company address line'. Any suggestions?

**Comment by MhLiao** [comment]
@moooood You can try other tricks to enlarge the receptive field, such as PPM.
