### ISSUE TITLE
预测出的property map如何进行二值化，阈值选择

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#72]
既然网络中可以学习到threshhold map，为什么在预测的时候不用他，然后这个thresh要自己去调试，这样子会不会影响鲁棒性呢？不同的图片，效果会不一样的吧？

**Comment by MhLiao** [comment]
@LanWong1 可以用。但是我们发现用于不用对性能影响不大。

**Comment by LanWong1** [comment]
但是用了的话，是不是可以不用去试threshold  直接用预测出来的threashold map来取阈值？这样针对不同的图片是不是效果会好点？

**Comment by MhLiao** [comment]
@LanWong1 你可以试试，不需要重新训练。
