### ISSUE TITLE
the threhold label 

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#73]
![图片](https://user-images.githubusercontent.com/33218397/70958998-e0265780-20b5-11ea-8cca-aeb680cf71d2.png)

![Uploading 图片.png…]()

您好，这里有一个问题，这里的标签是距离，但是在后面求loss的时候，也是距离，好像跟这个标签没有关系。threshold map预测出来的是一些坐标吗？不然怎么求距离呢？但这坐标点的个数怎么确定呢？是根据lable确定的吧？

**Comment by wanzysky** [comment]
预测出来的值都是[0,1]上的float值，不直接表征距离。对于一个点(x, y), 通过计算最近的线段的距离得到渐进的值。具体实现可以参考https://github.com/MhLiao/DB/blob/master/data/processes/make_border_map.py

**Comment by LJXLJXLJX** [comment]
@wanzysky 您好，请问为什么thresh map不直接使用和probability map 与 binary map一样的损失函数呢？
