### ISSUE TITLE
效果一般

### ISSUE THREAD

**Issue by chen849157649** [MhLiao/DB#74]
![1](https://user-images.githubusercontent.com/32058220/70986160-58157180-20f8-11ea-956a-88857d996562.jpg)
![2](https://user-images.githubusercontent.com/32058220/70986161-58ae0800-20f8-11ea-9cd4-40ba24d2fc6d.jpg)
![3](https://user-images.githubusercontent.com/32058220/70986162-58ae0800-20f8-11ea-8c28-fa541518a023.jpg)
![4](https://user-images.githubusercontent.com/32058220/70986164-58ae0800-20f8-11ea-9d3d-4e35e40ee569.jpg)
![8](https://user-images.githubusercontent.com/32058220/70986165-59469e80-20f8-11ea-862b-1930783c853c.jpg)
![10](https://user-images.githubusercontent.com/32058220/70986166-59469e80-20f8-11ea-993b-b5f664e229f9.jpg)

**Comment by MhLiao** [comment]
@chen849157649 请问你是否有重新用同一分布的训练集训练？

**Comment by chen849157649** [comment]
@MhLiao ，没有训练，直接测试的你预训练模型td500_resnet50

**Comment by MhLiao** [comment]
@chen849157649  如果要评估泛化能力应该是跟其他方法同等情况下对比。目前大部分的方法都是数据驱动的，不训练就测其他数据集说明不了什么。你可以看看TextField的Table V，换数据集掉点是非常显著的。

**Comment by jianbaba** [comment]
> @chen849157649 如果要评估泛化能力应该是跟其他方法同等情况下对比。目前大部分的方法都是数据驱动的，不训练就测其他数据集说明不了什么。你可以看看TextField的Table V，换数据集掉点是非常显著的。

请问，我训练了400epo了，但是设置是1200，大概多久能达到最好的的效果，还有怎么确定哪个模型的效果最好！
