### ISSUE TITLE
polygon_area

### ISSUE THREAD

**Issue by leigaoxiang** [MhLiao/DB#76]
def polygon_area(polygon):
    edge = 0
    for i in range(polygon.shape[0]):
        next_index = (i + 1) % polygon.shape[0]
        edge += (polygon[next_index, 0] - polygon[i, 0]) * (polygon[next_index, 1] - polygon[i, 1])

    return edge / 2.

how to compute polygon area? but the method you use is not easy to read?
thank you

**Comment by Shudeng** [comment]
Hello, @cqray1990 .
Have you figured out this problem? I am confused about the meaning of the function and doubt if it's used to calculate the area of polygon.

For example, let polygon be [[0,0], [0,1], [1,1], [[1,0]], this function would return 0 while the true area is 1.
