### ISSUE TITLE
resize 选择

### ISSUE THREAD

**Issue by hhhoushiyu** [MhLiao/DB#77]
您好，请问base*.yaml中这几处的resize 宽和高是怎么确定的？
![b424dd6f777c742fe782985336aa5e3](https://user-images.githubusercontent.com/49675570/71050938-9440e480-2181-11ea-9dc6-c68c8f75f3fa.png)
![777d8a649668233978a894741903593](https://user-images.githubusercontent.com/49675570/71050940-960aa800-2181-11ea-838c-b34c2bf891f7.png)
![48184ca1db60817e1e33c0cbdb0f294](https://user-images.githubusercontent.com/49675570/71050942-97d46b80-2181-11ea-867b-91b0e337706c.png)
感谢

**Comment by wanzysky** [comment]
这里是根据数据集本身的特点选择输入尺寸。
一方面考虑图片本身的分辨率和长宽比，另一方面考虑文字的scale变化。

**Comment by hhhoushiyu** [comment]
> 这里是根据数据集本身的特点选择输入尺寸。
> 一方面考虑图片本身的分辨率和长宽比，另一方面考虑文字的scale变化。

如果我的训练图片尺寸是2048x2048,应该如何设置尺寸呢

**Comment by wanzysky** [comment]
如果你希望以这个大小输入并且显存放得下的话可以直接写width和height 2048；不过建议等比例缩小到1/2或者1/4。

**Comment by hhhoushiyu** [comment]
使用自己的数据集训练时Loss一直为1，不知道是数据集哪里出了问题？
![微信图片_20191218150823](https://user-images.githubusercontent.com/49675570/71063804-7f2b7c00-21a8-11ea-9c5b-092c9af2be7b.png)
