### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by shaohailin** [MhLiao/DB#78]
![图片](https://user-images.githubusercontent.com/56865153/71055956-98c1c900-2192-11ea-8813-efea8d00e57a.png)
how to solve it?

**Comment by TyrionChou** [comment]
ZeroDivisionError: division by zero 是由于eval.py 代码175行的continue导致后面的内容没有计算，把continue注释就好了！

**Comment by Bachelorwangwei** [comment]
训练过程中也出现相同的问题，这可能是什么原因呢？是因为标签可能有误的原因吗？
