### ISSUE TITLE
多类别检测文本

### ISSUE THREAD

**Issue by yu1206** [MhLiao/DB#79]
文本字体有白色，黑色等，怎么在定位的同时分类出是白色字体，黑色字体。
研究了一下代码，数据读入的时候没有类别信息。检测目标的时候不是默认背景为0 目标为1么？
怎么修改让代码支持多类别检测？

**Comment by MhLiao** [comment]
@yu1206 我们没有考虑过这种需求，建议你自己读懂代码并修改。
