### ISSUE TITLE
运行demo报错：NotImplementedError

### ISSUE THREAD

**Issue by MissPenguin** [MhLiao/DB#80]
![image](https://user-images.githubusercontent.com/25809855/71073972-64630280-21bc-11ea-9526-ce66d16081a9.png)
对应代码：
![image](https://user-images.githubusercontent.com/25809855/71074050-8d839300-21bc-11ea-8fd2-6539f4473138.png)
请问是什么问题，该怎么弄呢？

**Comment by MhLiao** [comment]
DCN暂时不支持CPU，请使用GPU
