### ISSUE TITLE
MobileNet模型小 速度却更慢

### ISSUE THREAD

**Issue by LanWong1** [MhLiao/DB#84]
为什么我用mobilenet训练出来的模型在cpu上跑 ，模型更小，速度却比resnet18的更慢？

**Comment by MhLiao** [comment]
@LanWong1 我没试过mobilenet

**Comment by BowieHsu** [comment]
@LanWong1 你是直接用pytorch的cpu版本推理的吗？pytorch里面对于cpu的可分离卷积的优化不好，你可以用更有效率的cpu推理库来做这个工作

**Comment by LanWong1** [comment]
> @LanWong1 你是直接用pytorch的cpu版本推理的吗？pytorch里面对于cpu的可分离卷积的优化不好，你可以用更有效率的cpu推理库来做这个工作

是在GPU上运行的，resnet18是0.006s一张，mobilenetV2是0.1s/张  还不知道是什么原因
