### ISSUE TITLE
关于输出box的问题

### ISSUE THREAD

**Issue by wangbingok1118** [MhLiao/DB#89]
![image](https://user-images.githubusercontent.com/22719977/71394003-4a0ca700-264a-11ea-9dd7-45a857ca4b1a.png)
如图：输出Box太小，一部分文字在外面。造成这种的原因是模型方法问题啊，还是后处理过程中的问题啊？该如果改进啊？
麻烦大佬帮忙解答下啊，感谢感谢

**Comment by MhLiao** [comment]
@wangbingok1118 可以适当增大[unclip](https://github.com/MhLiao/DB/blob/b1b038495c856b72792e9400429b1475179357d9/structure/representers/seg_detector_representer.py#L145)的`unclip_ratio`
