### ISSUE TITLE
ground truth替换成二值化图像该怎么修改代码

### ISSUE THREAD

**Issue by seine7ee** [MhLiao/DB#91]
如果我要加载自己的数据集，但是我们的数据集的gt是二值化图像，并不是和您使用的数据集类似地坐标点的txt文件，而且每张图中标注的轮廓信息也并不完全是4个坐标点，例如，10个坐标点描述一个轮廓，或者7个坐标点描述一个轮廓，请问，我应该怎么修改代码？

**Comment by power630** [comment]
cv2.findCounters

**Comment by MhLiao** [comment]
@seine7ee 同意楼上。

**Comment by seine7ee** [comment]
多谢，已经改好了
