### ISSUE TITLE
训练时 dataLoader killed

### ISSUE THREAD

**Issue by snailsvincent** [MhLiao/DB#94]
请问训练时为什么会莫名其妙被killed 内存是够的
RuntimeError: DataLoader worker (pid 25902) is killed by signal: Segmentation fault

**Comment by 09876qwrte** [comment]
可能是你num_works设置太大了

**Comment by snailsvincent** [comment]
> 可能是你num_works设置太大了

设为1都被kill了

**Comment by MhLiao** [comment]
@snailsvincent 我没有遇到过这种情况，你试过其他数据集也一样吗？

**Comment by huihuixiaohuihui** [comment]
请问解决了没？我也遇到同样的问题
