### ISSUE TITLE
thresh map 的真值

### ISSUE THREAD

**Issue by xuannianz** [MhLiao/DB#97]
Hi @MhLiao ，大神我想请教下，最后在 thresh map 上生成的真值，距离 polygon 边界近的位置值较大，远的位置值较小，为什么要这么设置啊？因为边界附近的点较难区分？

**Comment by MhLiao** [comment]
@xuannianz 论文中有提到，是因为不加thresh map的监督的时候，模型能学出类似的效果，所以为了让训练更稳定，就加上了这样的监督。

**Comment by xuannianz** [comment]
谢谢。
